Repository dapr/dapr, pull requests merged in 2020-09, with the labels that each got.

#2097 adds postgres binding
  cmd/daprd/main.go
  go.sum
Labels: area/runtime/binding

#2104 adds rethinkdb state and binding components
  cmd/daprd/main.go
  go.mod
  go.sum
Labels: area/runtime/binding

#2141 Trustdomain value was ignored in ACL policy
  pkg/apis/configuration/v1alpha1/types.go
  pkg/apis/configuration/v1alpha1/zz_generated.deepcopy.go
  pkg/config/configuration_test.go
Labels: P0, kind/bug

#2152 Update Helm chart readme
  charts/dapr/README.md
Labels: do-not-merge

#2119 Add 0.11.0 release notes
  docs/release_notes/v0.11.0.md
Labels: do-not-merge
