Repository dapr/dapr, pull requests merged in 2020-07, with the labels that each got.

#1681 Initial commit of state store transactional API
  dapr/proto/runtime/v1/dapr.proto
  go.mod
  go.sum
  pkg/grpc/api.go
  pkg/grpc/api_test.go
  pkg/http/api.go
  pkg/http/api_test.go
  pkg/proto/runtime/v1/dapr.pb.go
  tests/apps/stateapp/app.go
  tests/apps/stateapp/go.mod
  tests/e2e/stateapp/stateapp_test.go
  tests/e2e/utils/helpers.go
Labels: do-not-merge

#1766 Fixes inappropriate HTTP API status codes #1765
  go.sum
  pkg/http/api.go
  pkg/http/api_test.go
Labels: P1, kind/bug

#1802 adds missing cron output binding
  cmd/daprd/main.go
Labels: area/runtime/binding

#1816 Fix to check traceparent header in gRPC metadata for grpc-dotnet client
  pkg/diagnostics/grpc_tracing.go
  pkg/diagnostics/http_tracing.go
  pkg/diagnostics/tracing.go
  pkg/diagnostics/tracing_test.go
  pkg/messaging/v1/util.go
Labels: kind/observability
