Repository dapr/dapr, pull requests merged in 2022-09, with the labels that each got.

#5114 Record metric for service updates
  pkg/operator/handlers/dapr_handler.go
Labels: automerge

#5101 upgrade tests go version to go1.19
  .build-tools/go.mod
  tests/apps/actorload/Dockerfile
  tests/apps/actorload/cmd/stateactor/main.go
  tests/apps/actorload/cmd/stateactor/service/server.go
  tests/apps/actorload/cmd/testclient/main.go
  tests/apps/actorload/go.mod
  tests/apps/actorload/go.sum
  tests/apps/actorload/pkg/actor/client/http/client.go
  tests/apps/actorload/pkg/telemetry/telemetry.go
  tests/apps/perf/actorfeatures/Dockerfile
  tests/apps/perf/actorfeatures/go.mod
  tests/apps/perf/service_invocation_grpc/Dockerfile
  tests/apps/perf/service_invocation_grpc/go.mod
  tests/apps/perf/service_invocation_http/.dockerignore
  tests/apps/perf/service_invocation_http/Dockerfile
  tests/apps/perf/service_invocation_http/go.mod
  tests/apps/perf/tester/Dockerfile
  tests/apps/perf/tester/go.mod
  tests/apps/resiliencyapp/go.mod
  tests/apps/resiliencyapp_grpc/go.mod
  tests/apps/service_invocation_grpc_proxy_client/go.mod
  tests/apps/service_invocation_grpc_proxy_server/go.mod
Labels: automerge

#5151 Kubernetes support for Pluggable Components
  charts/dapr/charts/dapr_rbac/templates/ClusterRoleBinding.yaml
  charts/dapr/crds/pluggable-components.yaml
  dapr/proto/operator/v1/operator.proto
  pkg/apis/components/v1alpha1/register.go
  pkg/apis/components/v1alpha1/types.go
  pkg/apis/components/v1alpha1/zz_generated.deepcopy.go
  pkg/components/pluggable/grpc.go
  pkg/components/pluggable/loader.go
  pkg/components/pluggable/loader_test.go
  pkg/operator/api/api.go
  pkg/operator/api/api_test.go
  pkg/proto/operator/v1/operator.pb.go
  pkg/proto/operator/v1/operator_grpc.pb.go
  pkg/runtime/runtime.go
  tests/apps/pluggable_redis/app.go
  tests/apps/pluggable_redis/go.mod
  tests/apps/pluggable_redis/go.sum
  tests/apps/stateapp/service.yaml
  tests/config/dapr_redis_pluggable_state.yaml
  tests/dapr_tests.mk
  tests/e2e/injector/injector_test.go
  tests/e2e/stateapp/stateapp_test.go
  tests/platforms/kubernetes/app_description.go
  tests/platforms/kubernetes/daprpluggable_component.go
  tests/platforms/kubernetes/daprpluggable_component_test.go
  tests/platforms/kubernetes/kubeobj.go
  tests/platforms/kubernetes/kubeobj_test.go
  tests/runner/kube_testplatform.go
  tests/runner/test_registry.go
  tests/runner/test_registry_test.go
Labels: do-not-merge

#5218 Fix E2E test login for ACR on Windows.
  .github/workflows/dapr-test.yml
Labels: autoupdate

#5208 Expose SecretStore and PubSub features through Metadata APIs.
  pkg/grpc/api_test.go
  pkg/http/api_test.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
  pkg/testing/pubsub_mock.go
  pkg/testing/secrets_mock.go
Labels: automerge

#5267 Increase tolerance in TestAppHealth_setResult
  pkg/apphealth/health_test.go
Labels: automerge
