Repository dapr/dapr, pull requests merged in 2022-11, with the labels that each got.

#5409 Changed API logging for HTTP to report abstract method name
  go.mod
  go.sum
  pkg/grpc/server.go
  pkg/grpc/server_test.go
  pkg/http/server.go
  pkg/http/server_test.go
  tests/apps/pluggable_kafka-bindings/go.mod
  tests/apps/pluggable_kafka-bindings/go.sum
  tests/apps/pluggable_redis-pubsub/go.mod
  tests/apps/pluggable_redis-pubsub/go.sum
  tests/apps/pluggable_redis-statestore/go.mod
  tests/apps/pluggable_redis-statestore/go.sum
Labels: documentation required

#5462 Added apiLogging options to config CRD
  charts/dapr/crds/configuration.yaml
  pkg/apis/configuration/v1alpha1/types.go
  pkg/apis/configuration/v1alpha1/zz_generated.deepcopy.go
  pkg/config/configuration.go
  pkg/http/api.go
  pkg/http/config.go
  pkg/http/endpoint.go
  pkg/http/server.go
  pkg/http/server_test.go
  pkg/injector/annotations/annotations.go
  pkg/injector/sidecar/container.go
  pkg/injector/sidecar/container_test.go
  pkg/runtime/cli.go
  pkg/runtime/runtime.go
Labels: automerge

#5494 Update pluggable interfaces to include `GetComponentMetadata` method
  pkg/components/bindings/input_pluggable.go
  pkg/components/bindings/output_pluggable.go
  pkg/components/pubsub/pluggable.go
  pkg/components/state/pluggable.go
Labels: automerge

#5566 Revert self-hosted AppID validation and only disallow dots
  pkg/runtime/cli.go
  pkg/validation/validation.go
  pkg/validation/validation_test.go
Labels: do-not-merge

#5538 Fix multiple race conditions when resiliency is enabled
  go.mod
  go.sum
  pkg/actors/actors.go
  pkg/diagnostics/resiliency_monitoring_test.go
  pkg/grpc/api.go
  pkg/grpc/api_test.go
  pkg/grpc/proxy/handler.go
  pkg/http/api.go
  pkg/http/api_test.go
  pkg/http/server.go
  pkg/messaging/direct_messaging.go
  pkg/messaging/v1/invoke_method_response.go
  pkg/resiliency/breaker/circuitbreaker.go
  pkg/resiliency/breaker/circuitbreaker_test.go
  pkg/resiliency/noop.go
  pkg/resiliency/noop_test.go
  pkg/resiliency/policy.go
  pkg/resiliency/policy_test.go
  pkg/resiliency/resiliency.go
  pkg/resiliency/resiliency_test.go
  pkg/runtime/bulk_subscriber.go
  pkg/runtime/pubsub/subscriptions.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
  pkg/testing/state_mock.go
  tests/apps/pluggable_kafka-bindings/go.mod
  tests/apps/pluggable_kafka-bindings/go.sum
  tests/apps/pluggable_redis-pubsub/go.mod
  tests/apps/pluggable_redis-pubsub/go.sum
  tests/apps/pluggable_redis-statestore/go.mod
  tests/apps/pluggable_redis-statestore/go.sum
  tests/apps/resiliencyapp/go.mod
  tests/apps/resiliencyapp/go.sum
  tests/apps/resiliencyapp_grpc/go.mod
  tests/apps/resiliencyapp_grpc/go.sum
  tests/apps/service_invocation_grpc_proxy_client/go.mod
  tests/apps/service_invocation_grpc_proxy_client/go.sum
Labels: do-not-merge
