Repository dapr/dapr, pull requests merged in 2023-09, with the labels that each got.

#6854 Change the default sentry serving port from 80 to 443
  charts/dapr/charts/dapr_placement/templates/dapr_placement_statefulset.yaml
  charts/dapr/charts/dapr_sentry/templates/dapr_sentry_service.yaml
  charts/dapr/charts/dapr_sentry/values.yaml
  charts/dapr/values.yaml
  cmd/placement/options/options.go
  pkg/injector/patcher/services.go
  pkg/injector/patcher/services_test.go
Labels: autoupdate

#6839 Report Dapr Actor API level (runtime version) to Placement
  dapr/proto/placement/v1/placement.proto
  pkg/actors/internal/api_level.go
  pkg/actors/placement/placement.go
  pkg/proto/placement/v1/placement.pb.go
Labels: autoupdate

#6193 [5756 Identity Management Overhaul] Operator
  charts/dapr/charts/dapr_config/templates/dapr_default_config.yaml
  charts/dapr/charts/dapr_operator/templates/dapr_operator_deployment.yaml
  cmd/operator/main.go
  cmd/operator/options/options.go
  pkg/operator/api/api.go
  pkg/operator/client/client.go
  pkg/operator/config.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/security/fake/fake.go
  pkg/security/security.go
  pkg/security/security_test.go
  pkg/security/x509source.go
  pkg/security/x509source_test.go
  pkg/sentry/server/server.go
  pkg/sentry/server/server_test.go
Labels: autoupdate

#6902 Allow the injector control plane service to request any identity from sentry
  pkg/sentry/sentry.go
  pkg/sentry/server/ca/ca.go
  pkg/sentry/server/ca/ca_test.go
  pkg/sentry/server/ca/fake/fake.go
  pkg/sentry/server/server.go
  pkg/sentry/server/server_test.go
  pkg/sentry/server/validator/fake/fake.go
  pkg/sentry/server/validator/insecure/insecure.go
  pkg/sentry/server/validator/internal/common.go
  pkg/sentry/server/validator/internal/common_test.go
  pkg/sentry/server/validator/jwks/jwks.go
  pkg/sentry/server/validator/kubernetes/kubernetes.go
  pkg/sentry/server/validator/kubernetes/kubernetes_test.go
  pkg/sentry/server/validator/validator.go
Labels: autoupdate

#6827 Actor State `ttlExpireTime`: Pipe `ttlExpireTime` to state responses
  dapr/proto/runtime/v1/dapr.proto
  pkg/actors/actors.go
  pkg/actors/requests_responses.go
  pkg/actors/transactional_state_request.go
  pkg/grpc/api.go
  pkg/grpc/api_actor_test.go
  pkg/http/api.go
  pkg/http/api_test.go
  pkg/http/responses_fasthttp.go
  pkg/http/responses_fasthttp_test.go
  pkg/proto/runtime/v1/dapr.pb.go
  tests/apps/actorstate/app.go
  tests/apps/stateapp/app.go
  tests/config/dapr_postgres_state.yaml
  tests/e2e/actor_state/actor_state_test.go
  tests/e2e/utils/http.go
  tests/integration/framework/process/daprd/daprd.go
  tests/integration/framework/process/daprd/options.go
  tests/integration/integration.go
  tests/integration/suite/actors/actors.go
  tests/integration/suite/actors/grpc/ttl.go
  tests/integration/suite/actors/http/ttl.go
  tests/integration/suite/daprd/state/grpc/ttl.go
  tests/integration/suite/daprd/state/http/ttl.go
Labels: autoupdate

#6823 Fix flaky e2e test actor_metadata
  tests/e2e/actor_metadata/actor_metadata_test.go
Labels: automerge

#6921 add unit test to cmd/placement/options
  cmd/placement/options/options_test.go
Labels: automerge

#6917 Placement: reduce verbosity of a debug log
  pkg/placement/membership.go
Labels: autoupdate

#6924 Makefile: tiny tweak for gen-proto
  Makefile
Labels: automerge

#6945 Remove deprecated RenameActorReminder methods
  dapr/proto/runtime/v1/dapr.proto
  pkg/actors/actors.go
  pkg/actors/actors_mock.go
  pkg/actors/internal/reminders.go
  pkg/actors/internal/requests.go
  pkg/actors/reminders/reminders.go
  pkg/actors/reminders/reminders_test.go
  pkg/actors/requests_responses.go
  pkg/grpc/api.go
  pkg/grpc/endpoints.go
  pkg/http/api.go
  pkg/http/api_test.go
  pkg/messages/predefined.go
  pkg/proto/runtime/v1/dapr.pb.go
  pkg/proto/runtime/v1/dapr_grpc.pb.go
  tests/apps/actorfeatures/app.go
  tests/e2e/actor_metadata/actor_metadata_test.go
  tests/e2e/actor_reminder/actor_reminder_test.go
Labels: breaking-change, autoupdate

#6959 Resiliency: add `GetAttempt` method for policy function
  pkg/actors/actors.go
  pkg/messaging/direct_messaging.go
  pkg/resiliency/policy.go
  pkg/resiliency/policy_test.go
Labels: autoupdate
