Repository dapr/dapr, pull requests merged in 2023-01, with the labels that each got.

#5648 Streaming support in `InternalInvokeRequest` / `InternalInvokeResponse`
  dapr/proto/common/v1/common.proto
  dapr/proto/runtime/v1/appcallback.proto
  dapr/proto/runtime/v1/dapr.proto
  pkg/actors/actors.go
  pkg/actors/actors_mock.go
  pkg/actors/actors_test.go
  pkg/channel/grpc/grpc_channel.go
  pkg/channel/grpc/grpc_channel_test.go
  pkg/channel/http/http_channel.go
  pkg/channel/http/http_channel_test.go
  pkg/channel/testing/channel_mock.go
  pkg/grpc/api.go
  pkg/grpc/api_daprinternal.go
  pkg/grpc/api_test.go
  pkg/grpc/auth.go
  pkg/grpc/endpoints.go
  pkg/grpc/server.go
  pkg/http/api.go
  pkg/http/api_test.go
  pkg/http/server.go
  pkg/messaging/direct_messaging.go
  pkg/messaging/direct_messaging_test.go
  pkg/messaging/v1/invoke_method_request.go
  pkg/messaging/v1/invoke_method_request_test.go
  pkg/messaging/v1/invoke_method_response.go
  pkg/messaging/v1/invoke_method_response_test.go
  pkg/messaging/v1/replayable_request.go
  pkg/proto/common/v1/common.pb.go
  pkg/proto/runtime/v1/dapr.pb.go
  pkg/resiliency/policy.go
  pkg/resiliency/resiliency.go
  pkg/runtime/bulk_subscriber.go
  pkg/runtime/bulk_subscriber_test.go
  pkg/runtime/pubsub/subscriptions.go
  pkg/runtime/pubsub/subscriptions_test.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
  pkg/testing/directmessaging_mock.go
  utils/byteslicepool.go
  utils/streams/multireadercloser.go
  utils/streams/teereadcloser.go
  utils/streams/testutils.go
Labels: autoupdate

#5646 Add resiliency to bulk publish API
  dapr/proto/runtime/v1/dapr.proto
  pkg/grpc/api.go
  pkg/http/api.go
  pkg/proto/runtime/v1/dapr.pb.go
  pkg/resiliency/breaker/circuitbreaker.go
  pkg/resiliency/resiliency.go
  pkg/runtime/pubsub/bulkpublish_resiliency.go
  pkg/runtime/pubsub/bulkpublish_resiliency_test.go
  pkg/runtime/pubsub/default_bulkpub.go
  pkg/runtime/runtime.go
  utils/utils.go
Labels: autoupdate

#5677 Allow enabling preview features at build-time
  Makefile
  cmd/injector/main.go
  cmd/operator/main.go
  cmd/placement/main.go
  cmd/sentry/main.go
  pkg/actors/actors.go
  pkg/actors/actors_test.go
  pkg/buildinfo/buildinfo.go
  pkg/buildinfo/buildinfo_unit.go
  pkg/config/configuration.go
  pkg/config/configuration_test.go
  pkg/grpc/api.go
  pkg/http/api.go
  pkg/runtime/cli.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
Labels: autoupdate

#5672 return error on duplicated entry IDs in gRPC bulk publish
  pkg/grpc/api.go
  pkg/grpc/api_test.go
Labels: autoupdate

#5716 Add metrics labels regex rules
  charts/dapr/crds/configuration.yaml
  pkg/apis/configuration/v1alpha1/types.go
  pkg/apis/configuration/v1alpha1/zz_generated.deepcopy.go
  pkg/config/configuration.go
  pkg/diagnostics/component_monitoring.go
  pkg/diagnostics/grpc_monitoring.go
  pkg/diagnostics/http_monitoring.go
  pkg/diagnostics/metrics.go
  pkg/diagnostics/metrics_regex_test.go
  pkg/diagnostics/resiliency_monitoring.go
  pkg/diagnostics/resiliency_monitoring_test.go
  pkg/diagnostics/service_monitoring.go
  pkg/diagnostics/utils/metrics_utils.go
  pkg/diagnostics/utils/metrics_utils_test.go
  pkg/injector/monitoring/metrics.go
  pkg/operator/monitoring/metrics.go
  pkg/runtime/runtime.go
  pkg/sentry/monitoring/metrics.go
Labels: documentation required

#5603 Resiliency Support for Bulk Subscribe
  pkg/runtime/bulk_subscriber.go
  pkg/runtime/bulk_subscriber_test.go
  pkg/runtime/bulksub_resiliency.go
  pkg/runtime/bulksub_resiliency_test.go
  pkg/runtime/pubsub/bulkpublish_resiliency.go
  pkg/runtime/runtime.go
  utils/utils.go
  utils/utils_test.go
Labels: autoupdate

#5752 Allow component metadata value to use {appID}
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
Labels: documentation required

#5769 Pin latest contrib and mqtt alias for mqtt3
  cmd/daprd/components/binding_mqtt.go
  cmd/daprd/components/pubsub_mqtt.go
  go.mod
  go.sum
  tests/apps/resiliencyapp/go.mod
  tests/apps/resiliencyapp/go.sum
  tests/apps/resiliencyapp_grpc/go.mod
  tests/apps/resiliencyapp_grpc/go.sum
  tests/apps/service_invocation_grpc_proxy_client/go.mod
  tests/apps/service_invocation_grpc_proxy_client/go.sum
Labels: automerge

#5770 Add DeepanshuA to dapr bot
  .github/scripts/dapr_bot.js
Labels: autoupdate

#5761 Dapr Workflow Engine Part 1: Internal Actors
  pkg/actors/actors.go
  pkg/actors/internal_actor.go
  pkg/actors/internal_actor_test.go
  pkg/messaging/v1/util.go
Labels: automerge

#5650 Add performance test for bulk subscribe over HTTP
  .build-tools/cmd/zz-e2e-perf.go
  tests/apps/perf/.gitignore
  tests/apps/perf/k6-custom/Dockerfile
  tests/apps/perf/pubsub_subscribe_http/.dockerignore
  tests/apps/perf/pubsub_subscribe_http/app.go
  tests/apps/perf/pubsub_subscribe_http/go.mod
  tests/apps/perf/pubsub_subscribe_http/go.sum
  tests/apps/perf/pubsub_subscribe_http/structs.go
  tests/apps/perf/pubsub_subscribe_http/subscribe.go
  tests/dapr_tests.mk
  tests/docs/running-perf-tests.md
  tests/perf/pubsub_bulk_subscribe_http/pubsub_bulk_subscribe_http_test.go
  tests/perf/pubsub_bulk_subscribe_http/test.js
Labels: automerge

#5786 Fixed log message
  pkg/runtime/runtime.go
Labels: autoupdate
