Repository dapr/dapr, pull requests merged in 2023-07, with the labels that each got.

#6367 Update Dapr Bot Action and respond to users that can't invoke commands
  .devcontainer/devcontainer.json
  .github/scripts/dapr_bot.js
  .github/workflows/dapr-bot.yml
  tests/perf/pubsub_bulk_publish_http/test.js
Labels: autoupdate

#6595 Convert all remaining Universal APIs to net/http and remove UniversalFastHTTPAdapter
  pkg/http/api.go
  pkg/http/api_workflow.go
  pkg/http/responses_fasthttp.go
  pkg/http/universalapi.go
  pkg/proto/runtime/v1/dapr_additional.go
  utils/fasthttpadaptor/README.md
  utils/fasthttpadaptor/adaptor.go
  utils/fasthttpadaptor/adaptor_test.go
  utils/fasthttpadaptor/request.go
  utils/fasthttpadaptor/request_test.go
Labels: autoupdate

#6558 Fixed race conditions in gRPC Configuration APIs
  pkg/grpc/api.go
  pkg/grpc/api_crypto_test.go
  pkg/grpc/api_test.go
  pkg/testing/store_mock.go
Labels: autoupdate

#6639 Stabilize middleware E2E test
  tests/e2e/middleware/middleware_test.go
Labels: autoupdate

#6638 Only use `gopkg.in/yaml.v3`
  .golangci.yml
  go.mod
  pkg/config/configuration.go
  pkg/httpendpoint/http_endpoint.go
  tests/perf/pubsub_subscribe_http/pubsub_subscribe_test.go
Labels: automerge, autoupdate

#6642 Healthcheck: add "appid" support (update of #6278)
  pkg/http/api.go
  pkg/http/api_test.go
  pkg/messages/predefined.go
Labels: autoupdate

#6651 Enable ServiceInvocationStreaming by default in builds
  Makefile
  pkg/channel/grpc/grpc_channel.go
  pkg/diagnostics/grpc_tracing.go
  pkg/grpc/api_daprinternal.go
Labels: autoupdate

#6674 reduce allocations on hot path for metrics
  pkg/diagnostics/grpc_monitoring.go
  pkg/diagnostics/utils/metrics_utils.go
Labels: autoupdate

#6594 Streaming: convert HTTP service invocation handler to net/http
  pkg/grpc/api.go
  pkg/http/api.go
  pkg/http/api_test.go
  pkg/messages/predefined.go
  pkg/messaging/v1/invoke_method_request_test.go
  pkg/messaging/v1/replayable_request_test.go
  tests/integration/suite/daprd/serviceinvocation/http/basic.go
  utils/streams/multireadercloser.go
Labels: autoupdate

#6670 Add "stablecomponents" tag to in-memory components
  cmd/daprd/components/pubsub_in-memory.go
  cmd/daprd/components/state_in-memory.go
Labels: autoupdate

#6667 Convert /healthz APIs to net/http
  pkg/http/api.go
  pkg/http/api_healthz.go
Labels: autoupdate

#6231 Adding postgres configuration component in E2E test
  .github/workflows/kind-e2e.yaml
  go.mod
  tests/apps/configurationapp/app.go
  tests/config/dapr_postgres_configuration.yaml
  tests/config/postgres_override.yaml
  tests/dapr_tests.mk
  tests/e2e/configuration/configuration_test.go
Labels: autoupdate

#6699 E2E: Run upgrade test with Dapr 1.10 and 1.11
  .github/workflows/dapr-test.yml
  .github/workflows/kind-e2e.yaml
  .gitignore
  .golangci.yml
  go.mod
  go.sum
  pkg/grpc/proxy/codec/codec.go
  tests/e2e/hellodapr/hellodapr_test.go
  tests/runner/summary/summary.go
Labels: autoupdate

#6673 tests/integration: Fix creating invalid file names for operating system
  tests/integration/framework/process/daprd/daprd.go
  tests/integration/framework/process/placement/placement.go
  tests/integration/framework/process/sentry/sentry.go
  tests/integration/framework/util/file.go
  tests/integration/framework/util/file_posix.go
  tests/integration/framework/util/file_windows.go
  tests/integration/framework/util/freeport.go
  tests/integration/suite/daprd/secret/http/compname.go
  tests/integration/suite/daprd/secret/http/fuzz.go
Labels: autoupdate

#6493 Fixed: operations on reminders should not be allowed if the sidecar isn't hosting actors of that type
  pkg/actors/actors.go
  pkg/actors/actors_test.go
  pkg/actors/config.go
  pkg/grpc/api.go
  pkg/http/api.go
  pkg/http/api_test.go
  pkg/messages/predefined.go
  tests/apps/actorfeatures/app.go
  tests/e2e/actor_reminder/actor_reminder_test.go
Labels: breaking-change, autoupdate

#6678 Registered azure openai component
  cmd/daprd/components/binding_azure_openai.go
  go.mod
  go.sum
Labels: autoupdate

#6669 Refactor actor reminders and timers into their own packages
  pkg/actors/actors.go
  pkg/actors/actors_mock.go
  pkg/actors/actors_test.go
  pkg/actors/config.go
  pkg/actors/config_test.go
  pkg/actors/internal/config.go
  pkg/actors/internal/placement_service.go
  pkg/actors/internal/reminder.go
  pkg/actors/internal/reminder_period.go
  pkg/actors/internal/reminder_period_test.go
  pkg/actors/internal/reminder_test.go
  pkg/actors/internal/reminder_track.go
  pkg/actors/internal/reminder_track_test.go
  pkg/actors/internal/reminders.go
  pkg/actors/internal/requests.go
  pkg/actors/internal/requests_test.go
  pkg/actors/internal/state.go
  pkg/actors/internal/timers.go
  pkg/actors/internal_actor_test.go
  pkg/actors/placement/client.go
  pkg/actors/placement/client_test.go
  pkg/actors/placement/grpc_opts.go
  pkg/actors/placement/placement.go
  pkg/actors/placement/placement_test.go
  pkg/actors/reminders/metadata.go
  pkg/actors/reminders/reminders.go
  pkg/actors/reminders/reminders_test.go
  pkg/actors/requests_responses.go
  pkg/actors/timers/timers.go
  pkg/actors/timers/timers_test.go
  pkg/diagnostics/resiliency_monitoring_test.go
  pkg/diagnostics/testutils_unit.go
  pkg/http/api_test.go
  pkg/runtime/wfengine/wfengine_test.go
Labels: autoupdate

#6650 Update pinned components-contrib
  .build-tools/go.mod
  .build-tools/go.sum
  go.mod
  go.sum
  pkg/actors/actors.go
  pkg/actors/actors_test.go
  pkg/components/bindings/input_pluggable.go
  pkg/components/bindings/output_pluggable.go
  pkg/components/pubsub/pluggable.go
  pkg/components/state/pluggable.go
  pkg/grpc/api.go
  pkg/grpc/api_test.go
  pkg/http/api.go
  pkg/http/api_test.go
  pkg/messages/predefined.go
  pkg/runtime/mock/mock.go
  pkg/runtime/processor/pubsub/bulk_subscriber_test.go
  pkg/runtime/processor/pubsub/pubsub_test.go
  pkg/runtime/runtime_test.go
  pkg/runtime/wfengine/component.go
  pkg/testing/bindings_mock.go
  pkg/testing/fake_state_store.go
  pkg/testing/lock_mock.go
  pkg/testing/nameresolution_mock.go
  pkg/testing/pubsub_mock.go
  pkg/testing/secrets_mock.go
  pkg/testing/state_mock.go
  pkg/testing/store_mock.go
  pkg/testing/subtlecrypto_mock.go
  pkg/testing/transactionalstore_mock.go
  pkg/testing/workflow_mock.go
  tests/apps/actorload/go.mod
  tests/apps/actorload/go.sum
  tests/apps/perf/actor-activation-locker/go.mod
  tests/apps/perf/actor-activation-locker/go.sum
  tests/apps/perf/service_invocation_grpc/go.mod
  tests/apps/perf/service_invocation_grpc/go.sum
  tests/apps/pluggable_kafka-bindings/go.mod
  tests/apps/pluggable_kafka-bindings/go.sum
  tests/apps/pluggable_redis-pubsub/go.mod
  tests/apps/pluggable_redis-pubsub/go.sum
  tests/apps/pluggable_redis-statestore/go.mod
  tests/apps/pluggable_redis-statestore/go.sum
  tests/apps/service_invocation_grpc_proxy_server/go.mod
  tests/apps/service_invocation_grpc_proxy_server/go.sum
Labels: autoupdate
