Repository dapr/dapr, pull requests merged in 2023-04, with the labels that each got.

#6206 Case-insensitive parsing of metadata properties `actorStateStore` and `keyPrefix`
  pkg/components/lock/lock_config.go
  pkg/components/lock/lock_config_test.go
  pkg/components/state/state_config.go
  pkg/components/state/state_config_test.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
Labels: documentation required

#6234 Fix panic in bulk publish while unmarshalling incorrect cloudevent
  pkg/http/api.go
  pkg/http/api_test.go
Labels: P1

#6253 Reduce QPS target for actor_reminder perf test
  tests/perf/actor_reminder/actor_reminder_test.go
Labels: automerge

#6192 Modify Actor type with details
  pkg/runtime/runtime.go
  pkg/runtime/wfengine/activity.go
  pkg/runtime/wfengine/activity_test.go
  pkg/runtime/wfengine/backend.go
  pkg/runtime/wfengine/wfengine.go
  pkg/runtime/wfengine/wfengine_test.go
  pkg/runtime/wfengine/workflow.go
  pkg/runtime/wfengine/workflowstate.go
  pkg/runtime/wfengine/workflowstate_test.go
  pkg/sentry/certs/store.go
  utils/utils.go
  utils/utils_test.go
Labels: breaking-change, automerge

#6136 [Crypto] Register local components
  cmd/daprd/components/crypto_dapr_jwks.go
  cmd/daprd/components/crypto_dapr_kubernetes_secrets.go
  cmd/daprd/components/crypto_dapr_localstorage.go
Labels: automerge, documentation required

#6237 Allow disabling Placement and Actors in Helm chart
  charts/dapr/README.md
  charts/dapr/charts/dapr_placement/templates/dapr_placement_poddisruptionbudget.yaml
  charts/dapr/charts/dapr_placement/templates/dapr_placement_service.yaml
  charts/dapr/charts/dapr_placement/templates/dapr_placement_statefulset.yaml
  charts/dapr/charts/dapr_sidecar_injector/templates/dapr_sidecar_injector_deployment.yaml
  charts/dapr/values.yaml
  pkg/injector/config.go
  pkg/injector/pod_patch.go
  pkg/injector/sidecar/container.go
  pkg/injector/sidecar/container_test.go
Labels: automerge

#6218 Workflow management API breaking changes for v1.11
  dapr/proto/runtime/v1/dapr.proto
  go.mod
  go.sum
  pkg/grpc/universalapi/api_workflow.go
  pkg/grpc/universalapi/api_workflow_test.go
  pkg/http/api.go
  pkg/http/api_test.go
  pkg/messages/predefined.go
  pkg/proto/runtime/v1/dapr.pb.go
  pkg/proto/runtime/v1/dapr_grpc.pb.go
  pkg/runtime/wfengine/README.md
  pkg/runtime/wfengine/backend.go
  pkg/runtime/wfengine/component.go
  pkg/runtime/wfengine/wfengine_test.go
  pkg/testing/workflow_mock.go
Labels: breaking-change

#6287 Actor metrics - incorporate feedback, add more tests, put some metrics tests to be common
  pkg/actors/actors.go
  pkg/actors/actors_test.go
  pkg/diagnostics/diagtestutils/testutils.go
  pkg/diagnostics/resiliency_monitoring_test.go
  pkg/diagnostics/service_monitoring.go
Labels: automerge
