Repository dapr/dapr, pull requests merged in 2023-10, with the labels that each got.

#6913 modify document of running E2E tests
  tests/docs/running-e2e-test.md
Labels: automerge

#6988 Fixed race conditions in Workflow E2E test
  tests/e2e/workflows/workflow_test.go
  tests/perf/workflows/workflow_test.go
Labels: autoupdate

#7021 Fix: Error immediately when metrics export server fails
  pkg/metrics/exporter.go
Labels: autoupdate

#6982 Integration test optimization 115s -> 80s
  Makefile
  tests/integration/framework/binary/binary.go
  tests/integration/framework/process/exec/iowriter/iowriter.go
  tests/integration/framework/process/exec/iowriter/iowriter_test.go
  tests/integration/framework/process/placement/placement.go
  tests/integration/framework/process/sentry/sentry.go
  tests/integration/framework/util/parallel.go
  tests/integration/suite/actors/healthz/healthz.go
  tests/integration/suite/actors/http/ttl.go
  tests/integration/suite/actors/reminders/rebalancing.go
  tests/integration/suite/daprd/httpserver/httpserver.go
  tests/integration/suite/daprd/mtls/kubernetes/disable.go
  tests/integration/suite/daprd/mtls/kubernetes/enable.go
  tests/integration/suite/daprd/mtls/standalone/disable.go
  tests/integration/suite/daprd/mtls/standalone/enable.go
  tests/integration/suite/daprd/pubsub/grpc/compname.go
  tests/integration/suite/daprd/pubsub/http/compname.go
  tests/integration/suite/daprd/pubsub/http/fuzz.go
  tests/integration/suite/daprd/secret/http/compname.go
  tests/integration/suite/daprd/secret/http/fuzz.go
  tests/integration/suite/daprd/serviceinvocation/grpc/basic.go
  tests/integration/suite/daprd/serviceinvocation/grpc/fuzz.go
  tests/integration/suite/daprd/serviceinvocation/http/basic.go
  tests/integration/suite/daprd/serviceinvocation/http/fuzz.go
  tests/integration/suite/daprd/serviceinvocation/http/httpendpoints.go
  tests/integration/suite/daprd/state/grpc/basic.go
  tests/integration/suite/daprd/state/grpc/compname.go
  tests/integration/suite/daprd/state/grpc/fuzz.go
  tests/integration/suite/daprd/state/http/basic.go
  tests/integration/suite/daprd/state/http/compname.go
  tests/integration/suite/daprd/state/http/fuzz.go
  tests/integration/suite/sentry/metrics/expiry.go
Labels: autoupdate

#7059 Update E2E test infra versions
  .github/workflows/dapr-perf-components.yml
  .github/workflows/dapr-perf.yml
  .github/workflows/dapr-test.yml
  .github/workflows/kind-e2e.yaml
  tests/test-infra/azure-aks.bicep
Labels: autoupdate

#7044 Adds basic actor reminder integration tests
  tests/integration/suite/actors/reminders/basic.go
  tests/integration/suite/actors/reminders/rebalancing.go
Labels: autoupdate

#7042 Update GitHub verison-skew workflow to use 1.12 setup components
  .github/workflows/version-skew-e2e.yaml
Labels: autoupdate

#7009 add ut for utils/http-middlewares
  utils/http-middlewares_test.go
Labels: automerge, autoupdate

#6918 E2E tests: Allow running actor invocation and reentrancy tests outside of K8s
  tests/apps/actorapp/app.go
  tests/apps/actorinvocationapp/.gitignore
  tests/apps/actorinvocationapp/app.go
  tests/apps/actorinvocationapp/resources/sqlite1.yaml
  tests/apps/actorinvocationapp/resources/sqlite2.yaml
  tests/apps/actorreentrancy/.gitignore
  tests/apps/actorreentrancy/app.go
  tests/apps/actorreentrancy/resources/sqlite.yaml
  tests/e2e/actor_invocation/actor_invocation_test.go
  tests/e2e/actor_reentrancy/actor_reentrancy_test.go
  tests/e2e/actor_reminder_partition/actor_reminder_partition_test.go
Labels: automerge, autoupdate

#7063 Retry windows wsaserror connection error in HTTPEndpoints TLS test
  tests/integration/suite/daprd/serviceinvocation/http/httpendpoints.go
Labels: automerge

#7070 e2e: Fix version-skew patch release directory env name
  .github/workflows/version-skew-e2e.yaml
Labels: autoupdate

#7080 Fix sentry rejecting legacy request IDs of length larger than 64
  pkg/sentry/sentry.go
  pkg/sentry/server/ca/ca.go
  pkg/sentry/server/validator/kubernetes/kubernetes.go
  pkg/sentry/server/validator/kubernetes/kubernetes_test.go
  tests/integration/framework/process/kubernetes/const.go
  tests/integration/framework/process/kubernetes/kubernetes.go
  tests/integration/framework/process/kubernetes/options.go
  tests/integration/framework/process/sentry/options.go
  tests/integration/framework/process/sentry/sentry.go
  tests/integration/suite/sentry/metrics/expiry.go
  tests/integration/suite/sentry/validator/insecure/insecure.go
  tests/integration/suite/sentry/validator/jwks/jwks.go
  tests/integration/suite/sentry/validator/jwks/utils.go
  tests/integration/suite/sentry/validator/kubernetes/common.go
  tests/integration/suite/sentry/validator/kubernetes/kubernetes.go
  tests/integration/suite/sentry/validator/kubernetes/longname.go
  tests/integration/suite/sentry/validator/validator.go
Labels: autoupdate

#7082 [1.12] Fix sentry rejecting legacy request IDs of length larger than 64
  docs/release_notes/v1.12.1.md
  pkg/sentry/sentry.go
  pkg/sentry/server/ca/ca.go
  pkg/sentry/server/validator/kubernetes/kubernetes.go
  pkg/sentry/server/validator/kubernetes/kubernetes_test.go
  tests/integration/framework/process/kubernetes/const.go
  tests/integration/framework/process/kubernetes/kubernetes.go
  tests/integration/framework/process/kubernetes/options.go
  tests/integration/framework/process/sentry/options.go
  tests/integration/framework/process/sentry/sentry.go
  tests/integration/suite/sentry/metrics/metrics.go
  tests/integration/suite/sentry/validator/insecure/insecure.go
  tests/integration/suite/sentry/validator/jwks/jwks.go
  tests/integration/suite/sentry/validator/jwks/utils.go
  tests/integration/suite/sentry/validator/kubernetes/common.go
  tests/integration/suite/sentry/validator/kubernetes/kubernetes.go
  tests/integration/suite/sentry/validator/kubernetes/longname.go
  tests/integration/suite/sentry/validator/validator.go
Labels: autoupdate

#7072 Integration: Fix wsarecv check on Windows TLS service invocation
  tests/integration/suite/daprd/serviceinvocation/http/httpendpoints.go
Labels: autoupdate

#7071 Integration: Fix Actor healthz/healthz test
  tests/integration/suite/actors/healthz/healthz.go
Labels: autoupdate

#7073 Integration: don't print binary build logs on test failure
  tests/integration/framework/binary/binary.go
  tests/integration/framework/iowriter/iowriter.go
  tests/integration/framework/iowriter/iowriter_test.go
  tests/integration/framework/process/exec/exec.go
  tests/integration/integration.go
Labels: automerge, autoupdate

#7096 Tiny tweaks in `utils`
  utils/kubernetes.go
  utils/utils.go
  utils/utils_test.go
Labels: automerge, autoupdate

#7105 Integration: fix race condition in daprd outbox test
  tests/integration/suite/daprd/outbox/http/basic.go
Labels: autoupdate

#7112 Placement: Adds authorization to ReportDaprStatus
  cmd/placement/main.go
  pkg/placement/placement.go
  pkg/placement/placement_test.go
  pkg/security/fake/fake.go
  pkg/security/fake/fake_test.go
  pkg/security/security.go
  tests/integration/suite/placement/authz/mtls.go
  tests/integration/suite/placement/authz/nomtls.go
  tests/integration/suite/placement/placement.go
  tests/integration/suite/placement/quorum/insecure.go
  tests/integration/suite/placement/quorum/jwks.go
Labels: autoupdate
