Repository dapr/dapr, pull requests merged in 2023-03, with the labels that each got.

#5991 Update pinned components-contrib
  Makefile
  cmd/daprd/components/binding_twitter.go
  go.mod
  go.sum
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
  tests/apps/resiliencyapp/go.mod
  tests/apps/resiliencyapp/go.sum
  tests/apps/resiliencyapp_grpc/go.mod
  tests/apps/resiliencyapp_grpc/go.sum
  tests/apps/service_invocation_grpc_proxy_client/go.mod
  tests/apps/service_invocation_grpc_proxy_client/go.sum
Labels: automerge, documentation required

#5997 Alias `bindings.azure.servicebusqueues` to `bindings.azure.servicebus.queues`
  cmd/daprd/components/binding_azure_servicebus_queues.go
Labels: automerge, docs-needed

#6061 Fixed typo in devcontainer.json
  .devcontainer/devcontainer.json
Labels: automerge

#5159 Distinguish between retriable and non-retriable error When publish a …
  pkg/runtime/init_error.go
  pkg/runtime/retriable_error.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
Labels: automerge

#6078 Set Minimum TLS version to 1.2 for AppChannel's HTTP and gRPC clients
  pkg/channel/channel.go
  pkg/channel/http/http_channel.go
  pkg/channel/http/http_channel_test.go
  pkg/config/configuration.go
  pkg/grpc/grpc.go
  pkg/runtime/runtime.go
Labels: breaking-change

#6094 Add Min TLS 1.2 for operator/ placement server / client and injector server
  pkg/credentials/grpc.go
  pkg/injector/injector.go
  pkg/operator/client/client.go
Labels: breaking-change

#6116 Convert lock APIs to Universal and fix inconsistencies
  dapr/proto/runtime/v1/dapr.proto
  pkg/grpc/api.go
  pkg/grpc/api_test.go
  pkg/grpc/universalapi/api_lock.go
  pkg/grpc/universalapi/universalapi.go
  pkg/http/api.go
  pkg/http/api_lock.go
  pkg/http/api_test.go
  pkg/http/universalapi.go
  pkg/messages/predefined.go
  pkg/proto/runtime/v1/dapr.pb.go
Labels: breaking-change
