Repository dapr/dapr, pull requests merged in 2024-06, with the labels that each got.

#7780 Fix buildx from arm64
  docker/docker.mk
Labels: automerge, autoupdate

#7757 Subscriptions: bi-directional subscription streaming- subscribe on no healthz.
  pkg/api/grpc/grpc.go
  pkg/api/grpc/grpc_test.go
  pkg/api/grpc/subscribe.go
  pkg/api/http/http.go
  pkg/api/http/http_test.go
  pkg/api/universal/metadata_test.go
  pkg/outbox/fake/fake.go
  pkg/outbox/fake/fake_test.go
  pkg/runtime/compstore/compstore.go
  pkg/runtime/compstore/pubsub.go
  pkg/runtime/compstore/subscriptions.go
  pkg/runtime/hotreload/reconciler/subscriptions.go
  pkg/runtime/processor/manager.go
  pkg/runtime/processor/processor.go
  pkg/runtime/processor/pubsub/pubsub.go
  pkg/runtime/processor/pubsub/pubsub_test.go
  pkg/runtime/processor/pubsub/subscribe.go
  pkg/runtime/processor/state/state_test.go
  pkg/runtime/processor/subscriber/subscriber.go
  pkg/runtime/processor/subscriber/subscriber_test.go
  pkg/runtime/processor/subscriptions.go
  pkg/runtime/pubsub/adapter.go
  pkg/runtime/pubsub/adapter_test.go
  pkg/runtime/pubsub/outbox.go
  pkg/runtime/pubsub/outbox_test.go
  pkg/runtime/pubsub/publisher/fake/fake.go
  pkg/runtime/pubsub/publisher/fake/fake_test.go
  pkg/runtime/pubsub/publisher/publisher.go
  pkg/runtime/pubsub/publisher/publisher_test.go
  pkg/runtime/pubsub/streamer/conn.go
  pkg/runtime/pubsub/streamer/streamer.go
  pkg/runtime/runtime.go
  pkg/runtime/subscription/bulkresiliency.go
  pkg/runtime/subscription/bulkresiliency_test.go
  pkg/runtime/subscription/bulksubscription.go
  pkg/runtime/subscription/bulksubscription_test.go
  pkg/runtime/subscription/publish.go
  pkg/runtime/subscription/publish_test.go
  pkg/runtime/subscription/subscription.go
  pkg/testing/pubsubadapter_mock.go
  tests/integration/suite/daprd/hotreload/selfhosted/subscriptions/stream/persist.go
  tests/integration/suite/daprd/hotreload/selfhosted/subscriptions/subscriptions.go
  tests/integration/suite/daprd/subscriptions/stream/errors.go
  tests/integration/suite/daprd/subscriptions/stream/healthz.go
Labels: P0, autoupdate

#7848 Update go-etcd-cron lib.
  go.mod
  go.sum
  pkg/api/grpc/grpc_test.go
  pkg/api/grpc/proxy/handler_test.go
  pkg/channel/grpc/grpc_channel_test.go
  pkg/components/pluggable/discovery.go
  pkg/components/pluggable/grpc_test.go
  pkg/messaging/direct_messaging_test.go
  pkg/operator/client/client.go
  pkg/placement/placement_test.go
  pkg/scheduler/client/client.go
  pkg/security/sentry.go
  pkg/testing/manager_mock.go
  tests/apps/resiliencyapp/go.mod
  tests/apps/resiliencyapp/go.sum
  tests/apps/resiliencyapp_grpc/go.mod
  tests/apps/resiliencyapp_grpc/go.sum
  tests/apps/service_invocation_grpc_proxy_client/go.mod
  tests/apps/service_invocation_grpc_proxy_client/go.sum
  tests/integration/framework/process/statestore/statestore.go
  tests/integration/suite/daprd/mtls/standalone/disable.go
  tests/integration/suite/daprd/serviceinvocation/grpc/basic.go
  tests/integration/suite/daprd/workflow/basic.go
  tests/integration/suite/placement/quorum/insecure.go
  tests/integration/suite/placement/quorum/jwks.go
Labels: autoupdate

#7843 custom latency distribution
  charts/dapr/crds/configuration.yaml
  pkg/api/grpc/proxy/handler_test.go
  pkg/apis/configuration/v1alpha1/types.go
  pkg/apis/configuration/v1alpha1/zz_generated.deepcopy.go
  pkg/config/configuration.go
  pkg/config/configuration_test.go
  pkg/diagnostics/component_monitoring.go
  pkg/diagnostics/component_monitoring_test.go
  pkg/diagnostics/grpc_monitoring.go
  pkg/diagnostics/grpc_monitoring_test.go
  pkg/diagnostics/http_monitoring.go
  pkg/diagnostics/http_monitoring_benchmark_test.go
  pkg/diagnostics/http_monitoring_test.go
  pkg/diagnostics/metrics.go
  pkg/diagnostics/metrics_regex_test.go
  pkg/diagnostics/resiliency_monitoring.go
  pkg/diagnostics/resiliency_monitoring_test.go
  pkg/diagnostics/service_monitoring.go
  pkg/diagnostics/service_monitoring_test.go
  pkg/diagnostics/workflow_monitoring.go
  pkg/diagnostics/workflow_monitoring_test.go
  pkg/runtime/config.go
  tests/config/dapr_observability_test_config.yaml
  tests/integration/framework/process/daprd/daprd.go
  tests/integration/suite/daprd/metrics/http/cardinality/high.go
  tests/integration/suite/daprd/metrics/http/distributionbuckets/high.go
  tests/integration/suite/daprd/metrics/http/distributionbuckets/low.go
  tests/integration/suite/daprd/metrics/http/distributionbuckets/util.go
  tests/integration/suite/daprd/metrics/http/http.go
Labels: automerge, docs-needed

#7514 Test Integration: Hot Reload `spec.ignoreErrors`
  pkg/runtime/processor/components.go
  tests/integration/framework/process/logline/logline.go
  tests/integration/suite/daprd/hotreload/operator/ignoreerrors.go
  tests/integration/suite/daprd/hotreload/selfhosted/ignoreerrors.go
Labels: automerge, autoupdate
