Repository dapr/dapr, pull requests merged in 2024-09, with the labels that each got.

#8059 Fix outbox regression
  docs/release_notes/v1.14.2.md
  pkg/runtime/runtime.go
Labels: P0

#8046 fix(state store): capture kit err if applicable
  pkg/api/grpc/grpc.go
  pkg/api/grpc/grpc_test.go
  pkg/api/http/http.go
  pkg/api/http/http_test.go
  pkg/api/http/responses.go
  pkg/api/universal/state_query.go
  pkg/components/pluggable/errors.go
  pkg/components/state/pluggable.go
  tests/integration/framework/process/statestore/component.go
  tests/integration/framework/process/statestore/options.go
  tests/integration/suite/daprd/state/grpc/customerrors.go
  tests/integration/suite/daprd/state/http/customerrors.go
Labels: automerge

#8092 [1.14] Scheduler: Add options for ETCD storage options
  charts/dapr/charts/dapr_scheduler/templates/dapr_scheduler_statefulset.yaml
  charts/dapr/charts/dapr_scheduler/values.yaml
  cmd/scheduler/app/app.go
  cmd/scheduler/options/options.go
  pkg/scheduler/server/config.go
  pkg/scheduler/server/server.go
Labels: autoupdate

#8083 [1.14] Jobs: change HTTP Create data request body to JSON
  dapr/proto/internals/v1/jobs.proto
  pkg/api/http/jobs.go
  pkg/api/universal/jobs.go
  pkg/channel/channel.go
  pkg/channel/grpc/grpc_channel.go
  pkg/channel/http/http_channel.go
  pkg/channel/testing/channel_mock.go
  pkg/proto/internals/v1/jobs.pb.go
  pkg/runtime/scheduler/streamer.go
  pkg/testing/app_channel_mock.go
  tests/integration/framework/process/daprd/daprd.go
  tests/integration/framework/process/placement/placement.go
  tests/integration/suite/daprd/jobs/grpc/api.go
  tests/integration/suite/daprd/jobs/grpc/http.go
  tests/integration/suite/daprd/jobs/http/api.go
  tests/integration/suite/daprd/jobs/http/basic.go
  tests/integration/suite/daprd/jobs/http/fields.go
  tests/integration/suite/daprd/jobs/http/grpc.go
Labels: autoupdate

#8116 Merge release-1.14
  charts/dapr/README.md
  charts/dapr/charts/dapr_scheduler/values.yaml
  charts/dapr/charts/dapr_sidecar_injector/templates/dapr_sidecar_injector_deployment.yaml
  charts/dapr/templates/NOTES.txt
  cmd/scheduler/options/options.go
  dapr/proto/internals/v1/jobs.proto
  docs/release_notes/v1.14.3.md
  docs/release_notes/v1.14.4.md
  pkg/actors/placement/client.go
  pkg/actors/placement/client_test.go
  pkg/api/http/jobs.go
  pkg/api/universal/jobs.go
  pkg/channel/channel.go
  pkg/channel/grpc/grpc_channel.go
  pkg/channel/http/http_channel.go
  pkg/channel/testing/channel_mock.go
  pkg/injector/patcher/sidecar.go
  pkg/injector/patcher/sidecar_container.go
  pkg/injector/patcher/sidecar_container_test.go
  pkg/injector/service/config.go
  pkg/injector/service/config_test.go
  pkg/injector/service/pod_patch.go
  pkg/operator/api/api.go
  pkg/operator/api/httpendpoints.go
  pkg/operator/api/subscriptions.go
  pkg/placement/raft/ha_test.go
  pkg/proto/internals/v1/jobs.pb.go
  pkg/runtime/scheduler/streamer.go
  pkg/testing/app_channel_mock.go
  tests/integration/framework/process/daprd/daprd.go
  tests/integration/framework/process/placement/placement.go
  tests/integration/suite/daprd/jobs/grpc/api.go
  tests/integration/suite/daprd/jobs/grpc/http.go
  tests/integration/suite/daprd/jobs/http/api.go
  tests/integration/suite/daprd/jobs/http/basic.go
  tests/integration/suite/daprd/jobs/http/fields.go
  tests/integration/suite/daprd/jobs/http/grpc.go
Labels: autoupdate

#8082 Perf Test Fine Tuning
  tests/perf/actor_reminder/actor_reminder_test.go
Labels: automerge
