Repository dapr/dapr, pull requests merged in 2024-11, with the labels that each got.

#8250 Renaming conversation types to exclude "Alpha1"
  dapr/proto/runtime/v1/dapr.proto
  pkg/api/http/conversation.go
  pkg/api/universal/conversation.go
  pkg/proto/runtime/v1/dapr.pb.go
  pkg/proto/runtime/v1/dapr_grpc.pb.go
  pkg/proto/runtime/v1/dapr_tracing.go
  tests/integration/suite/daprd/conversation/grpc/basic.go
  tests/integration/suite/daprd/conversation/grpc/scrubpii.go
Labels: automerge, autoupdate

#8282 Skip Scheduler Reconnect Test on Windows
  tests/integration/suite/daprd/jobs/streaming/reconnect.go
Labels: automerge, autoupdate

#8000 Add support for test framework to run with local Kind cluster
  Makefile
  tests/dapr_tests.mk
  tests/docs/running-perf-tests.md
  tests/platforms/kubernetes/appmanager.go
  tests/platforms/kubernetes/client.go
Labels: automerge, autoupdate

#8263 sftp component register
  cmd/daprd/components/binding_sftp.go
  go.mod
  go.sum
Labels: automerge

#8260 chore: add logging to dapr-bot script
  .github/scripts/dapr_bot.js
Labels: autoupdate

#8257 Adds unit tests for different circuit breaker trip expressions
  pkg/resiliency/breaker/circuitbreaker.go
  pkg/resiliency/breaker/circuitbreaker_test.go
Labels: automerge

#8264 Unregister actor in placement
  pkg/placement/membership_test.go
  pkg/placement/placement.go
  pkg/placement/placement_test.go
  pkg/placement/raft/server.go
  pkg/placement/raft/state.go
  pkg/placement/raft/state_test.go
  tests/integration/suite/placement/dissemination/notls.go
Labels: autoupdate

#8301 Increase graceful shutdown duration for state components shutdown test
  tests/integration/suite/daprd/shutdown/block/app/pubsub/bulk.go
  tests/integration/suite/daprd/state/grpc/compname.go
Labels: automerge
