Repository dapr/dapr, pull requests merged in 2024-01, with the labels that each got.

#7281 Standardize initialization actor services: Placement and Reminders
  pkg/actors/actors.go
  pkg/actors/actors_mock.go
  pkg/actors/actors_test.go
  pkg/actors/internal/options.go
  pkg/actors/internal/placement_service.go
  pkg/actors/internal/reminders.go
  pkg/actors/placement/placement.go
  pkg/actors/placement/placement_test.go
  pkg/actors/reminders/reminders.go
  pkg/actors/reminders/reminders_test.go
Labels: P0, autoupdate

#7260 Hot Reloading: Kubernetes Component hot reloading
  pkg/apis/components/v1alpha1/register.go
  pkg/apis/httpEndpoint/v1alpha1/register.go
  pkg/config/configuration.go
  pkg/operator/api/api.go
  pkg/operator/api/api_test.go
  pkg/operator/operator.go
  pkg/runtime/compstore/crypto.go
  pkg/runtime/hotreload/hotreload.go
  pkg/runtime/hotreload/loader/operator/component.go
  pkg/runtime/hotreload/loader/operator/operator.go
  pkg/runtime/hotreload/loader/operator/resource.go
  pkg/runtime/hotreload/loader/operator/resource_test.go
  pkg/runtime/processor/pubsub/pubsub_test.go
  pkg/runtime/runtime.go
  pkg/security/security_test.go
  tests/config/preview_configurations.yaml
  tests/e2e/hotreloading/hotreloading_test.go
  tests/integration/framework/process/exec/exec.go
  tests/integration/framework/process/grpc/app/app.go
  tests/integration/framework/process/grpc/app/options.go
  tests/integration/framework/process/grpc/app/server.go
  tests/integration/framework/process/grpc/operator/operator.go
  tests/integration/framework/process/grpc/operator/options.go
  tests/integration/framework/process/grpc/operator/server.go
  tests/integration/framework/process/kubernetes/informer/informer.go
  tests/integration/framework/process/kubernetes/kubernetes.go
  tests/integration/framework/process/kubernetes/options.go
  tests/integration/framework/process/kubernetes/store/store.go
  tests/integration/framework/process/operator/operator.go
  tests/integration/framework/process/sentry/sentry.go
  tests/integration/import.go
  tests/integration/suite/daprd/binding/input/appready.go
  tests/integration/suite/daprd/hotreload/hotreload.go
  tests/integration/suite/daprd/hotreload/operator/binding/binding.go
  tests/integration/suite/daprd/hotreload/operator/binding/intput/grpc.go
  tests/integration/suite/daprd/hotreload/operator/binding/intput/http.go
  tests/integration/suite/daprd/hotreload/operator/binding/output.go
  tests/integration/suite/daprd/hotreload/operator/crypto.go
  tests/integration/suite/daprd/hotreload/operator/informer.go
  tests/integration/suite/daprd/hotreload/operator/middleware.go
  tests/integration/suite/daprd/hotreload/operator/operator.go
  tests/integration/suite/daprd/hotreload/operator/pubsub/grpc.go
  tests/integration/suite/daprd/hotreload/operator/pubsub/http.go
  tests/integration/suite/daprd/hotreload/operator/secret.go
  tests/integration/suite/daprd/hotreload/operator/state.go
  tests/integration/suite/daprd/hotreload/selfhosted/binding/input/grpc.go
  tests/integration/suite/daprd/hotreload/selfhosted/pubsub/grpc.go
  tests/integration/suite/daprd/hotreload/selfhosted/state.go
  tests/integration/suite/daprd/mtls/kubernetes/disable.go
  tests/integration/suite/daprd/mtls/kubernetes/enable.go
  tests/integration/suite/daprd/mtls/kubernetes/operator.go
  tests/integration/suite/daprd/outbox/grpc/basic.go
  tests/integration/suite/daprd/pubsub/grpc/appready.go
  tests/integration/suite/daprd/serviceinvocation/grpc/server.go
  tests/integration/suite/daprd/serviceinvocation/grpc/slowappstartup.go
  tests/integration/suite/operator/api/componentupdate.go
  tests/integration/suite/operator/api/listcomponents.go
  tests/integration/suite/operator/operator.go
  tests/integration/suite/placement/quorum/insecure.go
Labels: autoupdate

#7301 Version Skew Integration Tests
  .github/scripts/version-skew-test-patches/e2e/release-1.12/dapr-sidecar-master/0001-remove-actor-reminder-rename.patch
  .github/scripts/version-skew-test-patches/e2e/release-1.12/dapr-sidecar-master/0002-Remove-Deprecated-RenameReminder-API-from-tests.patch
  .github/scripts/version-skew-test-patches/e2e/release-1.12/dapr-sidecar-master/0003-Added-patch-for-updated-http_metrics-test-in-1.12.patch
  .github/scripts/version-skew-test-patches/integration/release-1.12/0001-go-verison-tls-error-message.patch
  .github/scripts/version-skew-test-patches/integration/release-1.12/0002-match-metadata-verison-for-1.12.patch
  .github/workflows/version-skew.yaml
Labels: autoupdate

#7276 Integration: adds daprd/resources/namespace test
  tests/integration/suite/daprd/resources/namespace.go
Labels: automerge, autoupdate

#7111 Operator: Adds authorization to the operator API
  cmd/injector/main.go
  cmd/placement/main.go
  cmd/sentry/main.go
  go.mod
  pkg/health/server.go
  pkg/operator/api/api.go
  pkg/operator/api/api_test.go
  pkg/operator/api/authz.go
  pkg/operator/api/authz_test.go
  pkg/operator/operator.go
  tests/e2e/service_invocation/service_invocation_test.go
  tests/integration/framework/process/grpcapp/grpcapp.go
  tests/integration/framework/process/grpcapp/options.go
  tests/integration/framework/process/grpcapp/server.go
  tests/integration/framework/process/kubernetes/informer/informer.go
  tests/integration/framework/process/kubernetes/options.go
  tests/integration/framework/process/sentry/options.go
  tests/integration/framework/process/sentry/sentry.go
  tests/integration/suite/daprd/hotreload/operator/informer.go
  tests/integration/suite/daprd/serviceinvocation/http/httpendpoints.go
  tests/integration/suite/healthz/operator.go
  tests/integration/suite/operator/api/authz.go
  tests/integration/suite/ports/operator.go
  tests/util/pki.go
Labels: P0, autoupdate

#7253 Helm: Add option to deploy Placement with zero replicas
  charts/dapr/README.md
  charts/dapr/charts/dapr_placement/templates/dapr_placement_statefulset.yaml
  charts/dapr/charts/dapr_placement/values.yaml
Labels: automerge, autoupdate

#7368 Fix integration version skew backwards compat failures
  .github/scripts/version-skew-test-patches/integration/release-1.12/0003-fix-actor-backwards-compat.patch
  .github/workflows/version-skew.yaml
Labels: autoupdate

#7106 Move all main implementation into app package for all binaries
  cmd/daprd/app/app.go
  cmd/daprd/main.go
  cmd/injector/app/app.go
  cmd/injector/main.go
  cmd/operator/app/app.go
  cmd/operator/main.go
  cmd/placement/app/app.go
  cmd/placement/main.go
  cmd/sentry/app/app.go
  cmd/sentry/main.go
Labels: autoupdate

#7296 Integration: Remove data race in: suite/actors/reminders/rebalancing.go
  tests/integration/framework/binary/binary.go
  tests/integration/framework/process/sqlite/options.go
  tests/integration/framework/process/sqlite/sqlite.go
  tests/integration/suite/actors/http/ttl.go
  tests/integration/suite/actors/reminders/rebalancing.go
  tests/integration/suite/actors/reminders/serialization/json.go
  tests/integration/suite/actors/reminders/serialization/protobuf.go
Labels: autoupdate

#7329 Switch gRPC sidecar-to-sidecar to create one connection per each pod
  go.mod
  go.sum
  pkg/api/grpc/manager/manager.go
  pkg/api/grpc/manager/pool.go
  pkg/api/grpc/server.go
  pkg/messaging/direct_messaging.go
  pkg/messaging/direct_messaging_test.go
  pkg/runtime/runtime.go
  tests/apps/resiliencyapp/go.mod
  tests/apps/resiliencyapp/go.sum
  tests/apps/resiliencyapp_grpc/go.mod
  tests/apps/resiliencyapp_grpc/go.sum
  tests/apps/service_invocation/app.go
  tests/apps/service_invocation_grpc_proxy_client/go.mod
  tests/apps/service_invocation_grpc_proxy_client/go.sum
  tests/e2e/service_invocation/service_invocation_test.go
  tests/perf/service_invocation_grpc/service_invocation_grpc_test.go
  tests/perf/service_invocation_http/service_invocation_http_test.go
Labels: autoupdate

#7283 Configure alternate backend for Dapr workflow
  .github/workflows/kind-e2e.yaml
  cmd/daprd/app/app.go
  cmd/daprd/components/wfbackend_actors.go
  cmd/daprd/components/wfbackend_sqlite.go
  pkg/api/http/http_test.go
  pkg/api/universal/universal.go
  pkg/api/universal/workflow.go
  pkg/api/universal/workflow_test.go
  pkg/components/category.go
  pkg/components/wfbackend/metadata.go
  pkg/components/wfbackend/registry.go
  pkg/components/wfbackend/registry_test.go
  pkg/components/wfbackend/wfbackend.go
  pkg/runtime/compstore/compstore.go
  pkg/runtime/meta/meta.go
  pkg/runtime/processor/manager.go
  pkg/runtime/processor/processor.go
  pkg/runtime/processor/wfbackend/wfbackend.go
  pkg/runtime/registry/options.go
  pkg/runtime/registry/registry.go
  pkg/runtime/runtime.go
  pkg/runtime/wfengine/backends/actors/activity_actor.go
  pkg/runtime/wfengine/backends/actors/backend.go
  pkg/runtime/wfengine/backends/actors/backend_test.go
  pkg/runtime/wfengine/backends/actors/workflow_actor.go
  pkg/runtime/wfengine/backends/actors/workflowstate.go
  pkg/runtime/wfengine/backends/sqlite/backend.go
  pkg/runtime/wfengine/backends/sqlite/metadata.go
  pkg/runtime/wfengine/component.go
  pkg/runtime/wfengine/wfengine.go
  pkg/runtime/wfengine/wfengine_test.go
  tests/apps/perf/k6-custom/Dockerfile
  tests/config/dapr_cosmosdb_state.yaml
  tests/config/dapr_cosmosdb_state_actorstore.yaml
  tests/config/dapr_postgres_state.yaml
  tests/config/dapr_postgres_state_actorstore.yaml
  tests/e2e/workflows/workflow_test.go
  tests/perf/workflows/workflow_test.go
Labels: P0, autoupdate

#7377 Test de-flaking & bug fixes
  .github/workflows/dapr.yml
  go.mod
  go.sum
  pkg/actors/timers/timers.go
  pkg/placement/placement_test.go
  pkg/runtime/mock/mock.go
  pkg/runtime/processor/binding/send_test.go
  pkg/sentry/server/validator/jwks/jwks.go
  tests/integration/framework/process/sentry/sentry.go
  tests/integration/framework/process/statestore/statestore.go
  tests/integration/framework/util/meta.go
  tests/integration/integration.go
  tests/integration/suite/actors/grpc/ttl.go
  tests/integration/suite/actors/healthz/initerror.go
  tests/integration/suite/actors/http/ttl.go
  tests/integration/suite/actors/reminders/basic.go
  tests/integration/suite/actors/reminders/rebalancing.go
  tests/integration/suite/actors/reminders/serialization/common.go
  tests/integration/suite/daprd/hotreload/operator/binding/intput/grpc.go
  tests/integration/suite/daprd/hotreload/operator/binding/intput/http.go
  tests/integration/suite/daprd/hotreload/operator/binding/output.go
  tests/integration/suite/daprd/hotreload/operator/crypto.go
  tests/integration/suite/daprd/hotreload/operator/informer.go
  tests/integration/suite/daprd/hotreload/operator/middleware.go
  tests/integration/suite/daprd/hotreload/operator/pubsub/grpc.go
  tests/integration/suite/daprd/hotreload/operator/pubsub/http.go
  tests/integration/suite/daprd/hotreload/operator/secret.go
  tests/integration/suite/daprd/hotreload/operator/state.go
  tests/integration/suite/daprd/hotreload/selfhosted/binding/input/grpc.go
  tests/integration/suite/daprd/hotreload/selfhosted/binding/input/http.go
  tests/integration/suite/daprd/hotreload/selfhosted/binding/output.go
  tests/integration/suite/daprd/hotreload/selfhosted/crypto.go
  tests/integration/suite/daprd/hotreload/selfhosted/middleware.go
  tests/integration/suite/daprd/hotreload/selfhosted/pubsub/grpc.go
  tests/integration/suite/daprd/hotreload/selfhosted/pubsub/http.go
  tests/integration/suite/daprd/hotreload/selfhosted/secret.go
  tests/integration/suite/daprd/hotreload/selfhosted/state.go
  tests/integration/suite/daprd/metrics/metrics.go
  tests/integration/suite/daprd/mtls/kubernetes/disable.go
  tests/integration/suite/daprd/resources/namespace.go
  tests/integration/suite/daprd/secret/http/fuzz.go
  tests/integration/suite/daprd/serviceinvocation/http/httpendpoints.go
  tests/integration/suite/daprd/state/grpc/errors.go
  tests/integration/suite/daprd/state/grpc/fuzz.go
  tests/integration/suite/daprd/state/http/errors.go
  tests/integration/suite/daprd/state/http/fuzz.go
  tests/integration/suite/placement/apilevel/no_max.go
  tests/integration/suite/placement/apilevel/shared.go
  tests/integration/suite/placement/apilevel/with_max.go
  tests/integration/suite/placement/apilevel/with_min.go
  tests/integration/suite/ports/operator.go
  tests/integration/suite/suite.go
Labels: autoupdate

#7376 Rewrite standalone memory and goroutine validation.
  .github/scripts/validate-sidecar-resources.sh
  .github/scripts/validate_sidecar_resources.py
  .github/workflows/dapr-standalone-validation.yml
Labels: autoupdate

#7385 Fix workflow subOrchestration creation
  pkg/runtime/wfengine/backends/actors/workflow_actor.go
  pkg/runtime/wfengine/wfengine_test.go
  tests/integration/suite/daprd/daprd.go
  tests/integration/suite/daprd/workflow/workflow.go
Labels: P0

#7322 PubSub API: standardize err msgs
  pkg/api/errors/errors.go
  pkg/api/errors/pubsub.go
  pkg/api/errors/state.go
  pkg/api/grpc/grpc.go
  pkg/api/http/http.go
  pkg/api/http/http_test.go
  pkg/api/http/responses_fasthttp.go
  pkg/api/universal/state_query.go
  pkg/messages/predefined.go
  pkg/runtime/processor/pubsub/publish.go
  pkg/runtime/pubsub/errors.go
  tests/integration/framework/process/pubsub/component.go
  tests/integration/framework/process/pubsub/in-memory/inmemory.go
  tests/integration/framework/process/pubsub/in-memory/options.go
  tests/integration/framework/process/pubsub/options.go
  tests/integration/framework/process/pubsub/pubsub.go
  tests/integration/suite/daprd/hotreload/operator/state.go
  tests/integration/suite/daprd/hotreload/selfhosted/state.go
  tests/integration/suite/daprd/pubsub/grpc/errors.go
  tests/integration/suite/daprd/pubsub/http/errors.go
  tests/integration/suite/daprd/state/grpc/errors.go
  tests/integration/suite/daprd/state/http/errors.go
Labels: autoupdate

#7348 Chore: update artifact actions
  .github/workflows/create-release.yaml
  .github/workflows/dapr-3rdparty-images.yaml
  .github/workflows/dapr-base-containers.yaml
  .github/workflows/dapr-bot-schedule.yml
  .github/workflows/dapr-bot.yml
  .github/workflows/dapr-dev-container.yml
  .github/workflows/dapr-perf-components.yml
  .github/workflows/dapr-perf.yml
  .github/workflows/dapr-release-notes.yml
  .github/workflows/dapr-standalone-validation.yml
  .github/workflows/dapr-test-sdk.yml
  .github/workflows/dapr-test.yml
  .github/workflows/dapr.yml
  .github/workflows/fossa.yml
  .github/workflows/kind-e2e.yaml
  .github/workflows/test-tooling.yml
  .github/workflows/version-skew.yaml
Labels: autoupdate

#7318 Allow specifying control plane service for actors and/or reminders
  charts/dapr/README.md
  charts/dapr/charts/dapr_placement/templates/dapr_placement_poddisruptionbudget.yaml
  charts/dapr/charts/dapr_placement/templates/dapr_placement_service.yaml
  charts/dapr/charts/dapr_placement/templates/dapr_placement_statefulset.yaml
  charts/dapr/charts/dapr_rbac/templates/placement.yaml
  charts/dapr/charts/dapr_sidecar_injector/templates/dapr_sidecar_injector_deployment.yaml
  charts/dapr/templates/_address_placement.tpl
  charts/dapr/values.yaml
  cmd/daprd/app/app.go
  cmd/daprd/options/options.go
  pkg/actors/actors.go
  pkg/actors/actors_test.go
  pkg/actors/config.go
  pkg/actors/config_test.go
  pkg/actors/internal/config.go
  pkg/actors/internal_actor_test.go
  pkg/actors/placement/placement.go
  pkg/actors/placement/placement_test.go
  pkg/actors/providers.go
  pkg/actors/providers_test.go
  pkg/actors/reminders/reminders_test.go
  pkg/injector/patcher/services.go
  pkg/injector/patcher/services_test.go
  pkg/injector/patcher/sidecar.go
  pkg/injector/patcher/sidecar_container.go
  pkg/injector/service/config.go
  pkg/injector/service/pod_patch.go
  pkg/runtime/config.go
  pkg/runtime/config_test.go
  pkg/runtime/processor/processor.go
  pkg/runtime/processor/state/state.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
  pkg/runtime/wfengine/backends/actors/backend_test.go
  pkg/runtime/wfengine/wfengine_test.go
  utils/utils.go
  utils/utils_test.go
Labels: autoupdate

#7022 Tune actor app health check to become healthy sooner
  pkg/actors/actors.go
  pkg/actors/actors_test.go
  pkg/actors/health/health.go
  pkg/actors/health/health_test.go
  pkg/actors/health/healthunit.go
  pkg/actors/placement/placement.go
  pkg/health/health.go
  pkg/health/health_test.go
Labels: autoupdate

#7340 Cascade terminate/Purge Workflow Support
  Makefile
  dapr/proto/runtime/v1/dapr.proto
  go.mod
  go.sum
  pkg/api/http/http.go
  pkg/api/http/http_test.go
  pkg/api/http/workflow.go
  pkg/api/universal/workflow.go
  pkg/proto/runtime/v1/dapr.pb.go
  pkg/runtime/wfengine/backends/actors/backend.go
  pkg/runtime/wfengine/component.go
  pkg/testing/workflow_mock.go
  tests/integration/suite/daprd/workflow/workflow.go
Labels: breaking-change, autoupdate, documentation required, docs-needed

#7391 Updated pinned components-contrib
  go.mod
  go.sum
  tests/apps/resiliencyapp/go.mod
  tests/apps/resiliencyapp/go.sum
  tests/apps/resiliencyapp_grpc/go.mod
  tests/apps/resiliencyapp_grpc/go.sum
  tests/apps/service_invocation_grpc_proxy_client/go.mod
  tests/apps/service_invocation_grpc_proxy_client/go.sum
  tests/integration/suite/daprd/hotreload/operator/crypto.go
  tests/integration/suite/daprd/hotreload/operator/informer.go
  tests/integration/suite/daprd/hotreload/operator/secret.go
  tests/integration/suite/daprd/hotreload/operator/state.go
  tests/integration/suite/daprd/hotreload/selfhosted/crypto.go
  tests/integration/suite/daprd/hotreload/selfhosted/secret.go
  tests/integration/suite/daprd/hotreload/selfhosted/state.go
  tests/integration/suite/daprd/resources/namespace.go
Labels: autoupdate

#7394 Adds actors healthz integration tests
  tests/integration/framework/process/daprd/daprd.go
  tests/integration/framework/process/http/http.go
  tests/integration/framework/process/http/options.go
  tests/integration/suite/actors/healthz/endpoint/allenabled.go
  tests/integration/suite/actors/healthz/endpoint/noapp.go
  tests/integration/suite/actors/healthz/endpoint/noappentities.go
  tests/integration/suite/actors/healthz/endpoint/noentities.go
  tests/integration/suite/actors/healthz/endpoint/path.go
  tests/integration/suite/actors/healthz/healthz.go
  tests/integration/suite/actors/healthz/initerror.go
Labels: P0, autoupdate

#7231 Internal and remote actor invocation optimization
  go.mod
  pkg/actors/actors.go
  pkg/actors/actors_mock.go
  pkg/actors/actors_test.go
  pkg/actors/errors/actor_error.go
  pkg/actors/internal_actor.go
  pkg/actors/internal_actor_test.go
  pkg/api/grpc/daprinternal.go
  pkg/api/grpc/grpc.go
  pkg/api/http/directmessaging_test.go
  pkg/api/http/http.go
  pkg/api/http/http_test.go
  pkg/messaging/v1/invoke_method_request.go
  pkg/messaging/v1/invoke_method_request_test.go
  pkg/messaging/v1/invoke_method_response.go
  pkg/messaging/v1/util.go
  pkg/messaging/v1/util_test.go
  pkg/proto/internals/v1/service_invocation_additional.go
  pkg/proto/internals/v1/service_invocation_additional_test.go
  pkg/proto/runtime/v1/dapr_additional.go
  pkg/runtime/wfengine/backends/actors/activity_actor.go
  pkg/runtime/wfengine/backends/actors/backend.go
  pkg/runtime/wfengine/backends/actors/workflow_actor.go
  pkg/runtime/wfengine/wfengine_test.go
  tests/e2e/actor_invocation/actor_invocation_test.go
Labels: autoupdate

#7401 Integration: flake on Windows (mtls standalone disable)
  tests/integration/suite/daprd/mtls/standalone/disable.go
Labels: autoupdate

#7400 Update placement API Level gRPC context key to `dapr-placement-api-level`
  pkg/actors/placement/client.go
  pkg/actors/placement/client_test.go
  pkg/placement/membership.go
  tests/integration/suite/placement/apilevel/shared.go
  tests/integration/suite/placement/authz/mtls.go
  tests/integration/suite/placement/authz/nomtls.go
  tests/integration/suite/placement/quorum/insecure.go
  tests/integration/suite/placement/quorum/jwks.go
  tests/integration/suite/placement/quorum/notls.go
Labels: autoupdate

#7041 Injector: Change daprd projected token audience to sentry SPIFFE ID
  cmd/injector/app/app.go
  pkg/injector/patcher/sidecar.go
  pkg/injector/patcher/sidecar_patcher_test.go
  pkg/injector/patcher/sidecar_volumes.go
  pkg/injector/service/injector.go
  pkg/injector/service/pod_patch.go
  pkg/security/consts/consts.go
Labels: P0, autoupdate

#7405 Remove workflow patch from vskew e2e tests
  .github/scripts/version-skew-test-patches/e2e/release-1.12/dapr-sidecar-master/0004-Setting-IngressPort-in-workflow-test.patch
Labels: automerge, autoupdate

#7417 Integration: remove time.Sleep and data race
  tests/integration/suite/daprd/workflow/workflow.go
Labels: autoupdate

#7214 Updates controller-runtime, remove WriteSVIDToDir
  go.mod
  go.sum
  pkg/operator/cache/cache.go
  pkg/operator/cache/cache_test.go
  pkg/operator/operator.go
  pkg/security/security.go
  pkg/security/x509source.go
  pkg/security/x509source_test.go
  pkg/testing/manager_mock.go
  tests/integration/framework/process/kubernetes/const.go
  tests/integration/framework/process/kubernetes/kubernetes.go
  tests/platforms/kubernetes/appmanager.go
  tests/runner/loadtest/k6.go
Labels: autoupdate

#7421 Fix pubsub metadata conflict
  pkg/messaging/v1/util.go
  tests/e2e/pubsub/pubsub_test.go
  tests/e2e/pubsub_grpc/pubsub_grpc_test.go
Labels: release-blocker, P0

#7432 Fix operator when healthz when running without webhooks
  pkg/operator/operator.go
Labels: P0

#7437 Nit: reserving folder for local dev in .gitignore.
  .gitignore
Labels: P2

#7427 Make Workflow `dapr` Component internal
  pkg/runtime/hotreload/differ/differ.go
  pkg/runtime/processor/processor.go
  pkg/runtime/processor/processor_test.go
  pkg/runtime/runtime.go
  pkg/runtime/wfengine/component.go
  tests/integration/framework/process/logline/logline.go
  tests/integration/suite/daprd/hotreload/operator/binding/intput/grpc.go
  tests/integration/suite/daprd/hotreload/operator/binding/intput/http.go
  tests/integration/suite/daprd/hotreload/operator/binding/output.go
  tests/integration/suite/daprd/hotreload/operator/crypto.go
  tests/integration/suite/daprd/hotreload/operator/informer.go
  tests/integration/suite/daprd/hotreload/operator/middleware.go
  tests/integration/suite/daprd/hotreload/operator/pubsub/grpc.go
  tests/integration/suite/daprd/hotreload/operator/pubsub/http.go
  tests/integration/suite/daprd/hotreload/operator/secret.go
  tests/integration/suite/daprd/hotreload/operator/state.go
  tests/integration/suite/daprd/hotreload/selfhosted/binding/input/grpc.go
  tests/integration/suite/daprd/hotreload/selfhosted/binding/input/http.go
  tests/integration/suite/daprd/hotreload/selfhosted/binding/output.go
  tests/integration/suite/daprd/hotreload/selfhosted/crypto.go
  tests/integration/suite/daprd/hotreload/selfhosted/middleware.go
  tests/integration/suite/daprd/hotreload/selfhosted/pubsub/grpc.go
  tests/integration/suite/daprd/hotreload/selfhosted/pubsub/http.go
  tests/integration/suite/daprd/hotreload/selfhosted/secret.go
  tests/integration/suite/daprd/hotreload/selfhosted/state.go
  tests/integration/suite/daprd/metrics/metrics.go
  tests/integration/suite/daprd/resources/dapr.go
  tests/integration/suite/daprd/resources/namespace.go
  tests/integration/suite/daprd/resources/workflow.go
  tests/integration/suite/daprd/secret/http/fuzz.go
  tests/integration/suite/daprd/shutdown/block/app/unhealthy.go
  tests/integration/suite/daprd/state/grpc/fuzz.go
  tests/integration/suite/daprd/state/http/fuzz.go
Labels: P0

#7418 Disable placement timeout with no peers
  pkg/actors/health/health.go
  pkg/actors/health/health_test.go
  pkg/placement/raft/server.go
Labels: autoupdate

#7399 Cherry picking changes from 1.12 that were not in master
  docs/release_notes/v1.12.3.md
  docs/release_notes/v1.12.4.md
  pkg/placement/membership.go
  pkg/placement/raft/server.go
  tests/integration/suite/actors/reminders/rebalancing.go
Labels: autoupdate
