Repository dapr/dapr, pull requests merged in 2024-10, with the labels that each got.

#8146 Linter: Update implementation code
  .golangci.yml
  cmd/placement/app/app.go
  cmd/placement/options/options_test.go
  pkg/actors/actor.go
  pkg/actors/actors.go
  pkg/actors/errors/actor_error.go
  pkg/actors/placement/placement.go
  pkg/actors/reminders/metadata.go
  pkg/actors/reminders/scheduler.go
  pkg/actors/reminders/statestore.go
  pkg/api/errors/pubsub.go
  pkg/api/grpc/daprinternal.go
  pkg/api/grpc/grpc.go
  pkg/api/grpc/manager/pool.go
  pkg/api/grpc/proxy/handler.go
  pkg/api/grpc/server.go
  pkg/api/http/actors.go
  pkg/api/http/directmessaging.go
  pkg/api/universal/jobs.go
  pkg/api/universal/metadata.go
  pkg/channel/grpc/grpc_channel.go
  pkg/channel/http/http_channel.go
  pkg/channel/http/rwrecorder.go
  pkg/components/state/registry.go
  pkg/diagnostics/grpc_tracing.go
  pkg/diagnostics/http_tracing.go
  pkg/diagnostics/tracing.go
  pkg/healthz/healthz.go
  pkg/injector/patcher/services.go
  pkg/injector/patcher/sidecar.go
  pkg/messaging/grpc_proxy.go
  pkg/operator/handlers/dapr_handler.go
  pkg/placement/hashing/consistent_hash.go
  pkg/placement/membership.go
  pkg/placement/raft/server.go
  pkg/placement/raft/state.go
  pkg/placement/tests/tests.go
  pkg/resiliency/resiliency.go
  pkg/runtime/authorizer/authorizer.go
  pkg/runtime/config.go
  pkg/runtime/processor/subscriber/subscriber.go
  pkg/runtime/pubsub/subscriptions.go
  pkg/runtime/runtime.go
  pkg/runtime/scheduler/clients/clients.go
  pkg/runtime/scheduler/scheduler.go
  pkg/runtime/scheduler/streamer.go
  pkg/runtime/wfengine/backends/actors/workflowstate.go
  pkg/scheduler/server/internal/pool.go
  pkg/sentry/config/config.go
  pkg/testing/component.go
  pkg/testing/directmessaging_mock.go
  pkg/testing/network.go
  pkg/validation/validation.go
  utils/utils.go
Labels: autoupdate

#8137 [1.14] Revert wf activity state, still prevent nil ptr
  pkg/runtime/wfengine/backends/actors/activity_actor.go
  pkg/runtime/wfengine/backends/actors/backend.go
  tests/docs/writing-integration-test.md
  tests/integration/framework/process/sqlite/options.go
  tests/integration/framework/process/sqlite/sqlite.go
Labels: autoupdate

#8139 Guaranteed FIFO invocation for actors
  pkg/actors/actor_lock.go
  pkg/actors/actors_mock.go
  pkg/actors/actors_test.go
  pkg/actors/internal/config.go
Labels: autoupdate

#8015 Configurable placement keep alive time, keep alive timeout and dissemination timeout
  charts/dapr/README.md
  charts/dapr/charts/dapr_placement/templates/dapr_placement_statefulset.yaml
  charts/dapr/charts/dapr_placement/values.yaml
  cmd/injector/options/options.go
  cmd/placement/app/app.go
  cmd/placement/options/options.go
  cmd/placement/options/options_test.go
  pkg/placement/membership.go
  pkg/placement/membership_test.go
  pkg/placement/placement.go
  pkg/placement/placement_test.go
Labels: automerge

#8158 Fix Jobs Key Path to Not be OS Specific
  go.mod
  go.sum
  tests/integration/suite/actors/reminders/scheduler/remove.go
  tests/integration/suite/daprd/jobs/remove.go
  tests/integration/suite/daprd/workflow/scheduler/deletereminder.go
  tests/integration/suite/scheduler/api/remove.go
  tests/integration/suite/scheduler/quorum/notls.go
Labels: autoupdate

#7982 Fix some flaky int tests
  pkg/actors/health/health_test.go
  tests/integration/suite/actors/reminders/scheduler/unregister.go
  tests/integration/suite/daprd/binding/input/appready.go
  tests/integration/suite/daprd/hotreload/operator/informer/scopes/components.go
  tests/integration/suite/daprd/metrics/http/excludeverbs/default.go
Labels: automerge

#8195 Integration Test: PII: use JSON equal for json string assertion
  tests/integration/suite/daprd/conversation/http/scrubpii.go
Labels: autoupdate

#8162 docs: fix upgrade dapr with helm link
  charts/dapr/README.md
Labels: automerge

#8091 [1.14] HTTP API: Remove "github.com/valyala/fasthttp"
  .github/workflows/dapr-perf-components.yml
  .github/workflows/dapr-perf.yml
  .github/workflows/dapr-test.yml
  go.mod
  pkg/api/http/endpoints/endpoint.go
  pkg/api/http/errors.go
  pkg/api/http/http.go
  pkg/api/http/http_test.go
  pkg/api/http/responses.go
  pkg/api/http/responses_fasthttp.go
  pkg/api/http/responses_fasthttp_test.go
  pkg/api/http/server.go
  pkg/diagnostics/http_monitoring.go
  pkg/diagnostics/http_tracing.go
  pkg/diagnostics/utils/trace_utils.go
  pkg/messaging/direct_messaging.go
  pkg/messaging/direct_messaging_test.go
  pkg/messaging/v1/invoke_method_request.go
  pkg/messaging/v1/invoke_method_response.go
  pkg/nethttpadaptor/nethttpadaptor.go
  pkg/nethttpadaptor/nethttpadaptor_test.go
  pkg/proto/internals/v1/service_invocation_additional.go
  tests/e2e/configuration/configuration_test.go
  tests/integration/framework/client/http.go
  tests/integration/framework/process/daprd/daprd.go
  tests/integration/suite/daprd/binding/output/memory.go
  tests/integration/suite/daprd/pluggable/basic.go
  tests/integration/suite/daprd/pubsub/http/errors.go
  tests/integration/suite/daprd/state/http/http.go
  tests/integration/suite/daprd/state/http/memory/getbulk.go
  tests/integration/suite/daprd/state/http/memory/save.go
  tests/integration/suite/daprd/state/http/memory/transaction.go
  tests/integration/suite/daprd/workflow/memory/scheduler.go
  tests/integration/suite/daprd/workflow/memory/state.go
Labels: autoupdate

#8202 [Perf] further fine tuning
  .github/workflows/dapr-standalone-validation.yml
  .github/workflows/kind-e2e.yaml
  tests/perf/actor_reminder/actor_reminder_test.go
Labels: automerge, autoupdate

#8150 Scheduler e2e Tests
  tests/apps/schedulerapp/app.go
  tests/apps/schedulerapp_grpc/app.go
  tests/e2e/actor_reminder/actor_reminder_test.go
  tests/e2e/scheduler/scheduler_test.go
Labels: automerge, autoupdate

#8157 Scheduler: ListJobs API
  dapr/proto/scheduler/v1/scheduler.proto
  go.mod
  go.sum
  pkg/proto/scheduler/v1/scheduler.pb.go
  pkg/proto/scheduler/v1/scheduler_grpc.pb.go
  pkg/scheduler/client/client.go
  pkg/scheduler/server/api.go
  pkg/scheduler/server/config.go
  pkg/scheduler/server/server.go
  tests/apps/resiliencyapp/go.mod
  tests/apps/resiliencyapp/go.sum
  tests/apps/resiliencyapp_grpc/go.mod
  tests/apps/resiliencyapp_grpc/go.sum
  tests/apps/service_invocation_grpc_proxy_client/go.mod
  tests/apps/service_invocation_grpc_proxy_client/go.sum
  tests/integration/framework/binary/binary.go
  tests/integration/framework/process/grpc/scheduler/options.go
  tests/integration/framework/process/grpc/scheduler/scheduler.go
  tests/integration/framework/process/grpc/scheduler/server.go
  tests/integration/framework/process/helm/helm.go
  tests/integration/framework/process/helm/options.go
  tests/integration/framework/process/scheduler/scheduler.go
  tests/integration/suite/actors/reminders/scheduler/remove.go
  tests/integration/suite/daprd/jobs/remove.go
  tests/integration/suite/daprd/workflow/scheduler/deletereminder.go
  tests/integration/suite/scheduler/api/api.go
  tests/integration/suite/scheduler/api/jobs.go
  tests/integration/suite/scheduler/api/list/crud.go
  tests/integration/suite/scheduler/api/list/data.go
  tests/integration/suite/scheduler/api/list/size.go
  tests/integration/suite/scheduler/api/remove.go
  tests/integration/suite/scheduler/authz/mtls.go
  tests/integration/suite/scheduler/metrics/actors.go
  tests/platforms/kubernetes/appmanager_test.go
Labels: autoupdate

#8161 proto: updates protoc to 25.4
  .github/workflows/dapr.yml
  Makefile
  dapr/README.md
  dapr/proto/common/v1/README.md
  dapr/proto/components/v1/README.md
  dapr/proto/internals/v1/README.md
  dapr/proto/operator/v1/README.md
  dapr/proto/placement/v1/README.md
  dapr/proto/runtime/v1/README.md
  dapr/proto/sentry/v1/README.md
  docker/Dockerfile-dev
  docker/README.md
  docker/custom-scripts/install-dapr-tools.sh
  pkg/proto/common/v1/common.pb.go
  pkg/proto/components/v1/bindings.pb.go
  pkg/proto/components/v1/bindings_grpc.pb.go
  pkg/proto/components/v1/common.pb.go
  pkg/proto/components/v1/pubsub.pb.go
  pkg/proto/components/v1/pubsub_grpc.pb.go
  pkg/proto/components/v1/secretstore.pb.go
  pkg/proto/components/v1/secretstore_grpc.pb.go
  pkg/proto/components/v1/state.pb.go
  pkg/proto/components/v1/state_grpc.pb.go
  pkg/proto/internals/v1/apiversion.pb.go
  pkg/proto/internals/v1/jobs.pb.go
  pkg/proto/internals/v1/reminders.pb.go
  pkg/proto/internals/v1/service_invocation.pb.go
  pkg/proto/internals/v1/service_invocation_grpc.pb.go
  pkg/proto/internals/v1/status.pb.go
  pkg/proto/operator/v1/operator.pb.go
  pkg/proto/operator/v1/operator_grpc.pb.go
  pkg/proto/placement/v1/placement.pb.go
  pkg/proto/placement/v1/placement_grpc.pb.go
  pkg/proto/runtime/v1/appcallback.pb.go
  pkg/proto/runtime/v1/appcallback_grpc.pb.go
  pkg/proto/runtime/v1/dapr.pb.go
  pkg/proto/runtime/v1/dapr_grpc.pb.go
  pkg/proto/sentry/v1/sentry.pb.go
  pkg/proto/sentry/v1/sentry_grpc.pb.go
Labels: autoupdate

#8173 overwrite dapr-api-token with app token when sending local instead of…
  pkg/messaging/grpc_proxy.go
  pkg/messaging/grpc_proxy_test.go
Labels: automerge

#8037 ci(kind-e2e): upgrade k8s to 1.31/1.30/1.29 and bumps kind-action
  .github/workflows/kind-e2e.yaml
Labels: autoupdate
