Repository dapr/dapr, pull requests merged in 2024-04, with the labels that each got.

#7573 Switch to OTel ParentSampler for correct sampling behavior
  pkg/diagnostics/tracing_sampler.go
  pkg/diagnostics/tracing_test.go
Labels: automerge

#7683 fix: use new linter install link
  .build-tools/cmd/check-lint-version.go
Labels: automerge, autoupdate

#7619 Test Integration: Fix flaky secret & state fuzz tests
  tests/integration/suite/daprd/secret/http/fuzz.go
  tests/integration/suite/daprd/state/grpc/fuzz.go
  tests/integration/suite/daprd/state/http/fuzz.go
Labels: autoupdate

#7337 Allow canceling recurring reminders after execution for non-internal actors
  pkg/actors/actors.go
  tests/integration/suite/actors/reminders/basic.go
Labels: autoupdate

#7597 Test Integration: Component checks with scopes
  tests/integration/suite/daprd/hotreload/selfhosted/scope.go
Labels: autoupdate
