Repository dapr/dapr, pull requests merged in 2024-03, with the labels that each got.

#7586 Adds v1.13.0 release notes
  docs/release_notes/v1.13.0.md
Labels: autoupdate

#7585 Update protoc protobuffer transcompilers
  .github/workflows/dapr.yml
  Makefile
  dapr/README.md
  dapr/proto/common/v1/README.md
  dapr/proto/components/v1/README.md
  dapr/proto/internals/v1/README.md
  dapr/proto/operator/v1/README.md
  dapr/proto/placement/v1/README.md
  dapr/proto/runtime/v1/README.md
  dapr/proto/sentry/v1/README.md
  docker/Dockerfile-dev
  docker/README.md
  docker/custom-scripts/install-dapr-tools.sh
  pkg/apis/common/zz_generated.deepcopy.go
  pkg/apis/components/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/configuration/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/httpEndpoint/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/resiliency/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/subscriptions/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/subscriptions/v2alpha1/zz_generated.deepcopy.go
  pkg/proto/common/v1/common.pb.go
  pkg/proto/components/v1/bindings.pb.go
  pkg/proto/components/v1/bindings_grpc.pb.go
  pkg/proto/components/v1/common.pb.go
  pkg/proto/components/v1/pubsub.pb.go
  pkg/proto/components/v1/pubsub_grpc.pb.go
  pkg/proto/components/v1/secretstore.pb.go
  pkg/proto/components/v1/secretstore_grpc.pb.go
  pkg/proto/components/v1/state.pb.go
  pkg/proto/components/v1/state_grpc.pb.go
  pkg/proto/internals/v1/apiversion.pb.go
  pkg/proto/internals/v1/reminders.pb.go
  pkg/proto/internals/v1/service_invocation.pb.go
  pkg/proto/internals/v1/service_invocation_grpc.pb.go
  pkg/proto/internals/v1/status.pb.go
  pkg/proto/operator/v1/operator.pb.go
  pkg/proto/operator/v1/operator_grpc.pb.go
  pkg/proto/placement/v1/placement.pb.go
  pkg/proto/placement/v1/placement_grpc.pb.go
  pkg/proto/runtime/v1/appcallback.pb.go
  pkg/proto/runtime/v1/appcallback_grpc.pb.go
  pkg/proto/runtime/v1/dapr.pb.go
  pkg/proto/runtime/v1/dapr_grpc.pb.go
  pkg/proto/sentry/v1/sentry.pb.go
  pkg/proto/sentry/v1/sentry_grpc.pb.go
  tests/integration/suite/daprd/serviceinvocation/grpc/proto/test.v1.pb.go
  tests/integration/suite/daprd/serviceinvocation/grpc/proto/test.v1_grpc.pb.go
  tests/integration/suite/daprd/serviceinvocation/grpc/server.go
Labels: autoupdate

#7624 Test E2E: Update N-1 and N-2 images
  .github/workflows/dapr-test.yml
  .github/workflows/kind-e2e.yaml
Labels: autoupdate

#7569 chore: convert crypto APIs to net/http
  pkg/api/http/crypto.go
Labels: automerge, autoupdate

#7084 Remove the legacy port 80 from the sentry service
  charts/dapr/charts/dapr_sentry/templates/dapr_sentry_service.yaml
Labels: autoupdate

#7588 Refactor api/errors into builders
  pkg/api/errors/README.md
  pkg/api/errors/errors.go
  pkg/api/errors/pubsub.go
  pkg/api/errors/state.go
  pkg/api/grpc/grpc.go
  pkg/api/http/http.go
  pkg/api/universal/state_query.go
  pkg/components/state/state_config.go
  tests/integration/suite/daprd/pubsub/grpc/errors.go
  tests/integration/suite/daprd/pubsub/http/errors.go
  tests/integration/suite/daprd/state/grpc/errors.go
  tests/integration/suite/daprd/state/http/errors.go
Labels: autoupdate

#7623 Test Integration: reserve ports in ordered blocks
  tests/integration/framework/process/daprd/daprd.go
  tests/integration/framework/process/grpc/grpc.go
  tests/integration/framework/process/http/http.go
  tests/integration/framework/process/operator/operator.go
  tests/integration/framework/process/placement/placement.go
  tests/integration/framework/process/ports/ports.go
  tests/integration/framework/process/sentry/sentry.go
  tests/integration/framework/util/freeport.go
  tests/integration/suite/daprd/httpserver/httpserver.go
  tests/integration/suite/daprd/serviceinvocation/grpc/slowappstartup.go
  tests/integration/suite/placement/quorum/insecure.go
  tests/integration/suite/placement/quorum/jwks.go
  tests/integration/suite/placement/quorum/notls.go
Labels: autoupdate

#7590 Integration Test: Add link to talk about integration tests
  tests/docs/writing-integration-test.md
Labels: autoupdate

#7579 Runtime Manifest Loader Refactor
  pkg/components/components_loader.go
  pkg/components/disk_manifest_loader_test.go
  pkg/components/kubernetes_loader.go
  pkg/components/local_loader.go
  pkg/components/local_loader_test.go
  pkg/httpendpoint/http_endpoint.go
  pkg/httpendpoint/http_endpoint_handler.go
  pkg/httpendpoint/http_endpoint_loader.go
  pkg/httpendpoint/kubernetes_loader.go
  pkg/httpendpoint/local_loader.go
  pkg/httpendpoint/manifest_loader.go
  pkg/internal/loader/disk/disk.go
  pkg/internal/loader/disk/disk_test.go
  pkg/internal/loader/kubernetes/components.go
  pkg/internal/loader/kubernetes/components_test.go
  pkg/internal/loader/kubernetes/httpendpoints.go
  pkg/internal/loader/kubernetes/kubernetes.go
  pkg/internal/loader/loader.go
  pkg/runtime/authorizer/authorizer.go
  pkg/runtime/authorizer/authorizer_test.go
  pkg/runtime/hotreload/loader/disk/disk.go
  pkg/runtime/hotreload/loader/disk/resource.go
  pkg/runtime/hotreload/loader/disk/resource_test.go
  pkg/runtime/runtime.go
  tests/integration/framework/process/logline/logline.go
  tests/integration/suite/daprd/hotreload/selfhosted/namespace/set.go
  tests/integration/suite/daprd/hotreload/selfhosted/namespace/unset.go
  tests/integration/suite/daprd/resources/namespace/set/unique.go
  tests/integration/suite/daprd/resources/namespace/unset/unique.go
  tests/integration/suite/daprd/resources/uniquename.go
Labels: autoupdate

#7565 Always tick renewal check every minute
  pkg/security/x509source.go
  tests/integration/framework/process/grpc/sentry/options.go
  tests/integration/framework/process/grpc/sentry/sentry.go
  tests/integration/framework/process/grpc/sentry/server.go
  tests/integration/suite/daprd/mtls/renew.go
Labels: autoupdate

#7650 chore: update the go-sdk validation workflow
  .github/workflows/dapr-test-sdk.yml
Labels: autoupdate

#7568 chore: Convert actor HTTP APIs off fasthttp
  dapr/proto/runtime/v1/dapr.proto
  pkg/api/grpc/actor_test.go
  pkg/api/grpc/daprinternal.go
  pkg/api/grpc/grpc.go
  pkg/api/grpc/grpc_test.go
  pkg/api/http/actors.go
  pkg/api/http/directmessaging.go
  pkg/api/http/http.go
  pkg/api/http/http_test.go
  pkg/api/http/lock.go
  pkg/api/http/responses.go
  pkg/api/http/universal.go
  pkg/api/http/universal_test.go
  pkg/api/universal/actors.go
  pkg/messages/predefined.go
Labels: autoupdate

#7037 Removes legacy SPIFFE TLS clients and servers in favour of the new SPIRE TLS clients and servers.
  .github/scripts/version-skew-test-patches/integration/release-1.13/control-plane-master/0003-daprd-control-plane-trust-domain.patch
  .github/scripts/version-skew-test-patches/integration/release-1.13/dapr-sidecar-master/0003-daprd-control-plane-trust-domain.patch
  cmd/injector/app/app.go
  pkg/injector/patcher/sidecar.go
  pkg/injector/patcher/sidecar_container.go
  pkg/injector/patcher/sidecar_container_test.go
  pkg/injector/patcher/sidecar_patcher_test.go
  pkg/injector/sentry/sentry.go
  pkg/injector/service/handler_test.go
  pkg/injector/service/injector.go
  pkg/injector/service/pod_patch.go
  pkg/security/consts/consts.go
  pkg/security/legacy/legacy.go
  pkg/security/legacy/legacy_test.go
  pkg/security/security.go
  pkg/security/x509source.go
  pkg/sentry/sentry.go
  pkg/sentry/server/ca/ca.go
  pkg/sentry/server/ca/ca_test.go
  pkg/sentry/server/ca/cert.go
  pkg/sentry/server/ca/fake/fake.go
  pkg/sentry/server/server.go
  pkg/sentry/server/server_test.go
  pkg/sentry/server/validator/fake/fake.go
  pkg/sentry/server/validator/insecure/insecure.go
  pkg/sentry/server/validator/internal/common.go
  pkg/sentry/server/validator/internal/common_test.go
  pkg/sentry/server/validator/jwks/jwks.go
  pkg/sentry/server/validator/kubernetes/kubernetes.go
  pkg/sentry/server/validator/kubernetes/kubernetes_test.go
  pkg/sentry/server/validator/validator.go
  tests/integration/framework/process/daprd/daprd.go
  tests/integration/framework/process/daprd/options.go
  tests/integration/framework/process/kubernetes/kubernetes.go
  tests/integration/suite/daprd/hotreload/operator/informer/basic.go
  tests/integration/suite/daprd/hotreload/operator/informer/reconnect/components.go
  tests/integration/suite/healthz/injector.go
  tests/integration/suite/healthz/operator.go
  tests/integration/suite/ports/injector.go
  tests/integration/suite/ports/operator.go
  tests/integration/suite/sentry/validator/insecure/insecure.go
  tests/integration/suite/sentry/validator/jwks/shared.go
  tests/integration/suite/sentry/validator/jwks/utils.go
  tests/integration/suite/sentry/validator/kubernetes/common.go
  tests/integration/suite/sentry/validator/kubernetes/kube.go
  tests/integration/suite/sentry/validator/kubernetes/legacyid.go
  tests/integration/suite/sentry/validator/kubernetes/longname.go
Labels: P0, autoupdate

#7659 Fix incorrect content-length being sent to HTTP published message
  pkg/messaging/v1/invoke_method_request.go
  tests/integration/framework/process/daprd/options.go
  tests/integration/framework/process/grpc/app/app.go
  tests/integration/framework/process/grpc/app/options.go
  tests/integration/framework/process/grpc/app/server.go
  tests/integration/framework/process/grpc/subscriber/options.go
  tests/integration/framework/process/grpc/subscriber/subscriber.go
  tests/integration/framework/process/http/subscriber/subscriber.go
  tests/integration/framework/process/pubsub/component.go
  tests/integration/framework/process/pubsub/options.go
  tests/integration/framework/process/pubsub/pubsub.go
  tests/integration/framework/process/statestore/options.go
  tests/integration/framework/process/statestore/statestore.go
  tests/integration/framework/socket/socket.go
  tests/integration/suite/daprd/pluggable/basic.go
  tests/integration/suite/daprd/pubsub/contentlength/bulk.go
  tests/integration/suite/daprd/pubsub/contentlength/singular.go
  tests/integration/suite/daprd/pubsub/grpc/errors.go
  tests/integration/suite/daprd/pubsub/http/errors.go
  tests/integration/suite/daprd/pubsub/pubsub.go
  tests/integration/suite/daprd/serviceinvocation/grpc/contentlength.go
  tests/integration/suite/daprd/state/grpc/errors.go
  tests/integration/suite/daprd/state/http/errors.go
Labels: autoupdate
