Repository dapr/dapr, pull requests merged in 2025-06, with the labels that each got.

#8744 Update Etcd to v3.6.0
  go.mod
  go.sum
Labels: automerge, autoupdate

#8739 Updated go version used in devcontainer to 1.24.3
  docker/Dockerfile-dev
Labels: automerge, autoupdate

#8726 Scheduler server control loop
  dapr/proto/internals/v1/jobs.proto
  go.mod
  go.sum
  pkg/proto/internals/v1/apiversion.pb.go
  pkg/proto/internals/v1/jobs.pb.go
  pkg/proto/internals/v1/reminders.pb.go
  pkg/proto/internals/v1/service_invocation.pb.go
  pkg/proto/internals/v1/service_invocation_grpc.pb.go
  pkg/scheduler/server/fake/fake.go
  pkg/scheduler/server/internal/cron/cron.go
  pkg/scheduler/server/internal/pool/connection/connection.go
  pkg/scheduler/server/internal/pool/loops/connections/connections.go
  pkg/scheduler/server/internal/pool/loops/connections/connections_test.go
  pkg/scheduler/server/internal/pool/loops/fake/fake.go
  pkg/scheduler/server/internal/pool/loops/loops.go
  pkg/scheduler/server/internal/pool/loops/stream/stream.go
  pkg/scheduler/server/internal/pool/loops/stream/stream_test.go
  pkg/scheduler/server/internal/pool/pool.go
  pkg/scheduler/server/internal/pool/store/instance.go
  pkg/scheduler/server/internal/pool/store/namespace.go
  pkg/scheduler/server/internal/pool/store/store.go
  pkg/scheduler/server/internal/pool/stream.go
  tests/e2e/service_invocation/service_invocation_test.go
  tests/integration/suite/daprd/subscriptions/stream/ordering.go
  tests/integration/suite/scheduler/metrics/goroutines.go
Labels: autoupdate

#8721 chore: Use custom round robin implementation for placement raft servers
  pkg/actors/actors.go
  pkg/actors/internal/placement/client/client.go
  pkg/actors/internal/placement/client/client_test.go
  pkg/actors/internal/placement/client/connector/connector.go
  pkg/actors/internal/placement/client/connector/dnslookup/dnslookup.go
  pkg/actors/internal/placement/client/connector/dnslookup/dnslookup_test.go
  pkg/actors/internal/placement/client/connector/static/static.go
  pkg/actors/internal/placement/client/connector/static/static_test.go
  pkg/actors/internal/placement/placement.go
  pkg/runtime/runtime.go
Labels: automerge, autoupdate

#8766 [1.15] Fix Workflow state store contention
  docs/release_notes/v1.15.6.md
  pkg/actors/state/fake/fake.go
  pkg/actors/state/state.go
  pkg/actors/targets/workflow/activity.go
  pkg/actors/targets/workflow/workflow.go
  pkg/api/grpc/actor_test.go
  pkg/api/grpc/grpc.go
  pkg/api/http/actors.go
  pkg/api/http/http_test.go
  pkg/runtime/wfengine/state/state.go
Labels: automerge

#8731 Workflow: Prevent panic when no actor state store is configured
  pkg/actors/targets/workflow/invoke.go
  tests/integration/suite/daprd/workflow/nostatestore/grpc.go
  tests/integration/suite/daprd/workflow/nostatestore/http.go
  tests/integration/suite/daprd/workflow/nostatestore/workerclient.go
  tests/integration/suite/daprd/workflow/workflow.go
  tests/integration/suite/scheduler/authz/mtls.go
Labels: automerge, autoupdate

#8748 remove client-side rate limiter from injector
  cmd/injector/app/app.go
  utils/kubernetes.go
Labels: automerge, autoupdate

#8777 [1.15] Integration Test stability
  tests/integration/framework/process/workflow/options.go
  tests/integration/framework/process/workflow/workflow.go
  tests/integration/suite/daprd/jobs/streaming/stream.go
  tests/integration/suite/daprd/shutdown/block/app/pubsub/bulk.go
  tests/integration/suite/daprd/state/http/errors.go
  tests/integration/suite/daprd/workflow/fanout.go
  tests/integration/suite/daprd/workflow/reconnect.go
  tests/integration/suite/daprd/workflow/reconnect/activity.go
  tests/integration/suite/daprd/workflow/reconnect/crossactivity.go
  tests/integration/suite/daprd/workflow/reconnect/raiseevent.go
  tests/integration/suite/daprd/workflow/workflow.go
  tests/integration/suite/ports/placement.go
Labels: automerge, autoupdate

#8778 [1.15] Cherrypick injector ratelimiter
  cmd/injector/app/app.go
  docs/release_notes/v1.15.6.md
  utils/kubernetes.go
Labels: automerge, autoupdate

#8771 [1.15] Workflow: Allow non-stream Workflow Schedule
  docs/release_notes/v1.15.6.md
  pkg/runtime/wfengine/backends/actors/actors.go
  tests/integration/suite/daprd/workflow/listener/crud.go
  tests/integration/suite/daprd/workflow/listener/multi.go
  tests/integration/suite/daprd/workflow/listener/single.go
  tests/integration/suite/daprd/workflow/workflow.go
Labels: automerge, autoupdate

#8770 Update Max Concurrent Workflow Operations
  docs/release_notes/v1.15.6.md
  pkg/config/configuration.go
  pkg/config/configuration_test.go
Labels: automerge, autoupdate

#8758 Integration: Expand workflow timer tests
  tests/integration/suite/daprd/workflow/timer/base.go
  tests/integration/suite/daprd/workflow/timer/resumeearly.go
  tests/integration/suite/daprd/workflow/timer/resumelate.go
  tests/integration/suite/daprd/workflow/workflow.go
Labels: automerge, autoupdate

#8792 create workflow - retry on actor type not found
  pkg/actors/errors/errors.go
  pkg/actors/router/router.go
  pkg/actors/table/table.go
  pkg/actors/table/table_test.go
  pkg/runtime/wfengine/backends/actors/actors.go
Labels: automerge, autoupdate

#8791 Create workflow retry actor not found
  pkg/actors/engine/engine.go
  pkg/actors/errors/errors.go
  pkg/actors/table/table.go
  pkg/actors/table/table_test.go
  pkg/runtime/wfengine/backends/actors/actors.go
Labels: autoupdate

#8763 Workflow: Allow non-stream Workflow Schedule
  docs/release_notes/v1.15.6.md
  pkg/runtime/wfengine/backends/actors/actors.go
  tests/integration/suite/daprd/workflow/listener/crud.go
  tests/integration/suite/daprd/workflow/listener/multi.go
  tests/integration/suite/daprd/workflow/listener/single.go
  tests/integration/suite/daprd/workflow/workflow.go
Labels: automerge, autoupdate

#8799 [1.15] Fix Scheduler Deadlock under high load
  docs/release_notes/v1.15.6.md
  go.mod
  go.sum
  pkg/scheduler/server/internal/pool/pool.go
  pkg/scheduler/server/internal/pool/store/namespace.go
  tests/apps/resiliencyapp/go.mod
  tests/apps/resiliencyapp/go.sum
  tests/apps/resiliencyapp_grpc/go.mod
  tests/apps/resiliencyapp_grpc/go.sum
  tests/apps/service_invocation_grpc_proxy_client/go.mod
  tests/apps/service_invocation_grpc_proxy_client/go.sum
  tests/integration/suite/actors/lock/reminders/remote/goroutines.go
Labels: automerge, autoupdate

#8805 Update github action runner windows-2019 to windows-2025
  .github/workflows/dapr-base-containers.yaml
  .github/workflows/dapr-test.yml
  .github/workflows/dapr.yml
Labels: automerge, autoupdate

#8795 Add target names to the healthz checks
  cmd/injector/app/app.go
  pkg/actors/internal/placement/client/client.go
  pkg/actors/internal/placement/placement.go
  pkg/actors/internal/reminders/storage/scheduler/scheduler.go
  pkg/api/grpc/server.go
  pkg/api/http/http_test.go
  pkg/healthz/healthz.go
  pkg/healthz/healthz_test.go
  pkg/healthz/server/server.go
  pkg/healthz/target.go
  pkg/healthz/target_test.go
  pkg/injector/service/injector.go
  pkg/metrics/exporter.go
  pkg/operator/operator.go
  pkg/placement/placement.go
  pkg/placement/raft/server.go
  pkg/runtime/hotreload/reconciler/reconciler.go
  pkg/runtime/runtime.go
  pkg/runtime/scheduler/internal/handler/handler.go
  pkg/scheduler/server/internal/controller/controller.go
  pkg/scheduler/server/internal/etcd/etcd.go
  pkg/scheduler/server/server.go
  pkg/security/security.go
  pkg/sentry/server/server.go
  pkg/sentry/server/validator/jwks/jwks.go
  pkg/sentry/server/validator/kubernetes/kubernetes.go
Labels: automerge, autoupdate

#8811 [1.15] Move Scheduler Actor Type Reload to Placement client
  pkg/actors/internal/placement/client/client.go
  pkg/actors/internal/placement/placement.go
  pkg/runtime/wfengine/backends/actors/actors.go
  tests/integration/suite/daprd/serviceinvocation/grpc/fuzz.go
Labels: automerge, autoupdate

#8800 Int test: reduce number of tests for goroutine check
  tests/integration/framework/process/daprd/daprd.go
  tests/integration/suite/actors/lock/reminders/remote/goroutines.go
  tests/integration/suite/daprd/state/http/fuzz.go
Labels: automerge, autoupdate

#8825 [1.15] Fixed Kafka PubSub intermittently dropping messages while retrying
  docs/release_notes/v1.15.6.md
  go.mod
  go.sum
Labels: automerge

#8754 Add new Make target and fix DEBUG behaviour
  Makefile
  tests/dapr_tests.mk
Labels: automerge, autoupdate
