Repository dapr/dapr, pull requests merged in 2025-02, with the labels that each got.

#8399 Improve test stability
  tests/e2e/actor_features/actor_features_test.go
  tests/e2e/actor_reminder/actor_reminder_test.go
  tests/integration/suite/actors/lock/call/reentry/pertype/http.go
  tests/integration/suite/actors/timers/callback/grpc.go
  tests/integration/suite/daprd/secret/http/compname.go
  tests/integration/suite/daprd/serviceinvocation/http/httpendpoints.go
  tests/integration/suite/daprd/state/http/basic.go
  tests/integration/suite/daprd/state/http/errors.go
  tests/integration/suite/operator/api/componentupdate/scopes/addapp.go
  tests/integration/suite/operator/api/componentupdate/scopes/deleteapp.go
Labels: automerge

#8395 Scheduler: ETCD mTLS
  charts/dapr/charts/dapr_scheduler/templates/_helpers.tpl
  charts/dapr/charts/dapr_scheduler/templates/dapr_scheduler_service.yaml
  charts/dapr/charts/dapr_scheduler/templates/dapr_scheduler_statefulset.yaml
  charts/dapr/charts/dapr_scheduler/values.yaml
  cmd/scheduler/app/app.go
  cmd/scheduler/options/options.go
  go.mod
  pkg/scheduler/server/config.go
  pkg/scheduler/server/config_test.go
  pkg/scheduler/server/internal/cron/cron.go
  pkg/scheduler/server/server.go
  pkg/security/fake/fake.go
  pkg/security/security.go
  pkg/sentry/server/server.go
  tests/integration/framework/process/scheduler/cluster/cluster.go
  tests/integration/framework/process/scheduler/options.go
  tests/integration/framework/process/scheduler/scheduler.go
  tests/integration/suite/actors/reminders/migration/scheduler/noop.go
  tests/integration/suite/actors/reminders/migration/scheduler/overwrite.go
  tests/integration/suite/daprd/jobs/kubernetes/namespace.go
  tests/integration/suite/scheduler/helm/ha.go
  tests/integration/suite/scheduler/kubernetes/namespace.go
Labels: automerge, autoupdate

#8292 Skew tests update for 1.15
  .github/scripts/version-skew-test-patches/e2e/release-1.14/control-plane-master/0001-remove-sqlite-backend.patch
  .github/scripts/version-skew-test-patches/e2e/release-1.14/control-plane-master/0002-trim-whitespace-in-config-test.patch
  .github/scripts/version-skew-test-patches/e2e/release-1.14/dapr-sidecar-master/0001-remove-sqlite-backend.patch
  .github/scripts/version-skew-test-patches/e2e/release-1.14/dapr-sidecar-master/0002-trim-whitespace-in-config-test.patch
  .github/scripts/version-skew-test-patches/e2e/release-1.14/dapr-sidecar-master/0003-actors-scheduler-reminders.patch
  .github/scripts/version-skew-test-patches/integration/release-1.14/control-plane-master/0001-remove-workflowbacked-sqlite.patch
  .github/scripts/version-skew-test-patches/integration/release-1.14/control-plane-master/0002-daprd-metadata-version.patch
  .github/scripts/version-skew-test-patches/integration/release-1.14/control-plane-master/0003-removes-vnodes-test.patch
  .github/scripts/version-skew-test-patches/integration/release-1.14/dapr-sidecar-master/0002-update-pubsub-expected-error.patch
  .github/scripts/version-skew-test-patches/integration/release-1.14/dapr-sidecar-master/0003-placement-status.patch
  .github/scripts/version-skew-test-patches/integration/release-1.14/dapr-sidecar-master/0004-scheduler-error-codes.patch
  .github/scripts/version-skew-test-patches/integration/release-1.14/dapr-sidecar-master/0005-removes-workflow-backend.patch
  .github/scripts/version-skew-test-patches/integration/release-1.14/dapr-sidecar-master/0006-adds-sidecar-config-for-scheduler-reminders.patch
  .github/scripts/version-skew-test-patches/integration/release-1.14/dapr-sidecar-master/0007-actors-health-and-metadata.patch
  pkg/runtime/scheduler/scheduler.go
  tests/README.md
  tests/docs/version-skew-tests.md
Labels: automerge

#8510 [1.15] Conversation: change property name from message to content
  dapr/proto/runtime/v1/dapr.proto
  pkg/api/universal/conversation.go
  pkg/proto/runtime/v1/dapr.pb.go
  tests/integration/suite/daprd/conversation/grpc/basic.go
  tests/integration/suite/daprd/conversation/grpc/scrubpii.go
  tests/integration/suite/daprd/conversation/http/basic.go
  tests/integration/suite/daprd/conversation/http/scrubpii.go
Labels: docs-needed

#8525 fix workflows closing broadcaster subscriptions
  pkg/actors/targets/workflow/workflow.go
Labels: autoupdate

#8527 Fix unmarshalling legacy custom state
  pkg/runtime/wfengine/state/state.go
Labels: automerge, autoupdate
