Repository dapr/dapr, pull requests merged in 2025-08, with the labels that each got.

#8944 chore: Move overwrite flag in runtime
  dapr/proto/runtime/v1/dapr.proto
  pkg/api/universal/jobs.go
  pkg/proto/runtime/v1/dapr.pb.go
  tests/integration/suite/daprd/jobs/grpc/overwrite.go
Labels: automerge

#8943 ci: sync release branch workflow #3920
  .github/workflows/sync-release-branch.yaml
Labels: automerge

#8959 [1.16] Cherrypicks proto and logs
  dapr/proto/runtime/v1/dapr.proto
  pkg/api/universal/jobs.go
  pkg/proto/runtime/v1/dapr.pb.go
  pkg/runtime/hotreload/reconciler/reconciler.go
  tests/integration/suite/daprd/jobs/grpc/overwrite.go
Labels: automerge

#8988 [1.16] GH CI: Downgrade MacOS to 14
  .github/workflows/dapr.yml
  .github/workflows/test-tooling.yml
  tests/integration/framework/process/daprd/daprd.go
  tests/integration/suite/daprd/workflow/crossapp/suborchestrator/restart.go
Labels: automerge

#8984 [1.16] fix(diagnostics): redirect
  pkg/diagnostics/http_monitoring_path_matching.go
  pkg/diagnostics/http_monitoring_test.go
  tests/integration/framework/process/http/http.go
  tests/integration/framework/process/http/options.go
  tests/integration/suite/daprd/serviceinvocation/http/redirect.go
Labels: automerge, autoupdate

#9003 [1.16] Update deps
  go.mod
  go.sum
Labels: automerge

#9024 [1.16] Update dapr/durabletask-go & contrib
  go.mod
  go.sum
Labels: autoupdate
